// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddJobPositionToHandpieces : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Handpieces_JobId",
                table: "Handpieces");

            migrationBuilder.AddColumn<int>(
                name: "JobPosition",
                table: "Handpieces",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.Sql(
@"declare @jobId [uniqueidentifier]
declare @cursor cursor

set @cursor = cursor for select [Id] from [Jobs]
open @cursor
fetch next from @cursor into @jobId
while @@fetch_status = 0
begin
declare @position int = 0
update [Handpieces] set @position = @position + 1, [JobPosition] = @position where [JobId] = @jobId
fetch next from @cursor into @jobId
end

close @cursor
deallocate @cursor", suppressTransaction: true);

            migrationBuilder.CreateIndex(
                name: "IX_Handpieces_JobId_JobPosition",
                table: "Handpieces",
                columns: new[] { "JobId", "JobPosition" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Handpieces_JobId_JobPosition",
                table: "Handpieces");

            migrationBuilder.DropColumn(
                name: "JobPosition",
                table: "Handpieces");

            migrationBuilder.CreateIndex(
                name: "IX_Handpieces_JobId",
                table: "Handpieces",
                column: "JobId");
        }
    }
}
