// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddClientAppearances : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ClientAppearances",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    LogoId = table.Column<Guid>(nullable: false),
                    BackgroundImageId = table.Column<Guid>(nullable: false),
                    PrimaryColor = table.Column<string>(nullable: true),
                    SecondaryColor = table.Column<string>(nullable: true),
                    HeaderTextColor = table.Column<string>(nullable: true),
                    ClientId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ClientAppearances", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ClientAppearances_UploadedImages_BackgroundImageId",
                        column: x => x.BackgroundImageId,
                        principalTable: "UploadedImages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ClientAppearances_Clients_ClientId",
                        column: x => x.ClientId,
                        principalTable: "Clients",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ClientAppearances_UploadedImages_LogoId",
                        column: x => x.LogoId,
                        principalTable: "UploadedImages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ClientAppearances_BackgroundImageId",
                table: "ClientAppearances",
                column: "BackgroundImageId");

            migrationBuilder.CreateIndex(
                name: "IX_ClientAppearances_ClientId",
                table: "ClientAppearances",
                column: "ClientId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ClientAppearances_LogoId",
                table: "ClientAppearances",
                column: "LogoId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ClientAppearances");
        }
    }
}
