// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class ChangeSignatureCreatorOfNotes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ClientNotes_Users_CreatorId",
                table: "ClientNotes");

            migrationBuilder.Sql("TRUNCATE TABLE [ClientNotes]");

            migrationBuilder.AddForeignKey(
                name: "FK_ClientNotes_Employees_CreatorId",
                table: "ClientNotes",
                column: "CreatorId",
                principalTable: "Employees",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ClientNotes_Employees_CreatorId",
                table: "ClientNotes");

            migrationBuilder.Sql("TRUNCATE TABLE [ClientNotes]");

            migrationBuilder.AddForeignKey(
                name: "FK_ClientNotes_Users_CreatorId",
                table: "ClientNotes",
                column: "CreatorId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
