// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHandpieceImages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HandpieceImages",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Date = table.Column<DateTime>(nullable: false),
                    ImageId = table.Column<Guid>(nullable: false),
                    HandpieceId = table.Column<Guid>(nullable: false),
                    Display = table.Column<bool>(nullable: false, defaultValue: false),
                    Description = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceImages", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HandpieceImages_Handpieces_HandpieceId",
                        column: x => x.HandpieceId,
                        principalTable: "Handpieces",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_HandpieceImages_UploadedImages_ImageId",
                        column: x => x.ImageId,
                        principalTable: "UploadedImages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceImages_HandpieceId",
                table: "HandpieceImages",
                column: "HandpieceId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceImages_ImageId",
                table: "HandpieceImages",
                column: "ImageId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HandpieceImages");
        }
    }
}
