// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddCorporateAppearances : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "CorporateNo",
                table: "Corporates",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "UrlPath",
                table: "Corporates",
                maxLength: 200,
                nullable: true);

            migrationBuilder.Sql(@"
declare @sequence int
set @sequence = 0
update [Corporates] set @sequence = @sequence + 1, [CorporateNo] = @sequence
update [Corporates] set [UrlPath] = 'Corporate' + cast([CorporateNo] as nvarchar(10))", suppressTransaction: true);

            migrationBuilder.AlterColumn<int>(
                name: "CorporateNo",
                table: "Corporates",
                nullable: false);

            migrationBuilder.AlterColumn<string>(
                name: "UrlPath",
                table: "Corporates",
                maxLength: 200,
                nullable: false);

            migrationBuilder.CreateTable(
                name: "CorporateAppearances",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    CorporateId = table.Column<Guid>(nullable: false),
                    LogoId = table.Column<Guid>(nullable: true),
                    BackgroundImageId = table.Column<Guid>(nullable: true),
                    PrimaryColor = table.Column<string>(nullable: true),
                    SecondaryColor = table.Column<string>(nullable: true),
                    HeaderTextColor = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CorporateAppearances", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CorporateAppearances_UploadedImages_BackgroundImageId",
                        column: x => x.BackgroundImageId,
                        principalTable: "UploadedImages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CorporateAppearances_Corporates_CorporateId",
                        column: x => x.CorporateId,
                        principalTable: "Corporates",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CorporateAppearances_UploadedImages_LogoId",
                        column: x => x.LogoId,
                        principalTable: "UploadedImages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Corporates_CorporateNo",
                table: "Corporates",
                column: "CorporateNo",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Corporates_UrlPath",
                table: "Corporates",
                column: "UrlPath",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_CorporateAppearances_BackgroundImageId",
                table: "CorporateAppearances",
                column: "BackgroundImageId");

            migrationBuilder.CreateIndex(
                name: "IX_CorporateAppearances_CorporateId",
                table: "CorporateAppearances",
                column: "CorporateId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_CorporateAppearances_LogoId",
                table: "CorporateAppearances",
                column: "LogoId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CorporateAppearances");

            migrationBuilder.DropIndex(
                name: "IX_Corporates_CorporateNo",
                table: "Corporates");

            migrationBuilder.DropIndex(
                name: "IX_Corporates_UrlPath",
                table: "Corporates");

            migrationBuilder.DropColumn(
                name: "CorporateNo",
                table: "Corporates");

            migrationBuilder.DropColumn(
                name: "UrlPath",
                table: "Corporates");
        }
    }
}
