// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddCommentsToHandpieces : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "InternalComment",
                table: "Handpieces",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PublicComment",
                table: "Handpieces",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "InternalComment",
                table: "Handpieces");

            migrationBuilder.DropColumn(
                name: "PublicComment",
                table: "Handpieces");
        }
    }
}
