// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class CreateHandpieceDiagnostics : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<decimal>(
                name: "InvoicedCost",
                table: "Handpieces",
                type: "decimal(18,2)",
                nullable: false,
                oldClrType: typeof(decimal));

            migrationBuilder.AlterColumn<decimal>(
                name: "CostOfRepair",
                table: "Handpieces",
                type: "decimal(18,2)",
                nullable: false,
                oldClrType: typeof(decimal));

            migrationBuilder.CreateTable(
                name: "HandpieceDiagnostics",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    HandpieceId = table.Column<Guid>(nullable: false),
                    ItemId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceDiagnostics", x => new { x.HandpieceId, x.ItemId });
                    table.ForeignKey(
                        name: "FK_HandpieceDiagnostics_Handpieces_HandpieceId",
                        column: x => x.HandpieceId,
                        principalTable: "Handpieces",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_HandpieceDiagnostics_DiagnosticCheckItems_ItemId",
                        column: x => x.ItemId,
                        principalTable: "DiagnosticCheckItems",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceDiagnostics_ItemId",
                table: "HandpieceDiagnostics",
                column: "ItemId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HandpieceDiagnostics");

            migrationBuilder.AlterColumn<decimal>(
                name: "InvoicedCost",
                table: "Handpieces",
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "decimal(18,2)");

            migrationBuilder.AlterColumn<decimal>(
                name: "CostOfRepair",
                table: "Handpieces",
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "decimal(18,2)");
        }
    }
}
