// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddCreatorToJobsAndHandpieces : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "CreatorId",
                table: "Jobs",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "CreatorId",
                table: "Handpieces",
                nullable: true);

            migrationBuilder.Sql(
                @"declare @id uniqueidentifier
select top 1 @id = [Id] from [Employees] order by [Type] desc, [LastName], [FirstName]

if @@ROWCOUNT > 0 begin
  update [Jobs] set [CreatorId] = @id
  update [Handpieces] set [CreatorId] = @id
end else begin
  delete from [HandpieceDiagnostics]
  delete from [HandpieceImages]
  delete from [Handpieces]
  delete from [JobInvoices]
  delete from [Jobs]
end", suppressTransaction: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "CreatorId",
                table: "Jobs",
                nullable: false);

            migrationBuilder.AlterColumn<Guid>(
                name: "CreatorId",
                table: "Handpieces",
                nullable: false);

            migrationBuilder.CreateIndex(
                name: "IX_Jobs_CreatorId",
                table: "Jobs",
                column: "CreatorId");

            migrationBuilder.CreateIndex(
                name: "IX_Handpieces_CreatorId",
                table: "Handpieces",
                column: "CreatorId");

            migrationBuilder.AddForeignKey(
                name: "FK_Handpieces_Employees_CreatorId",
                table: "Handpieces",
                column: "CreatorId",
                principalTable: "Employees",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Jobs_Employees_CreatorId",
                table: "Jobs",
                column: "CreatorId",
                principalTable: "Employees",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Handpieces_Employees_CreatorId",
                table: "Handpieces");

            migrationBuilder.DropForeignKey(
                name: "FK_Jobs_Employees_CreatorId",
                table: "Jobs");

            migrationBuilder.DropIndex(
                name: "IX_Jobs_CreatorId",
                table: "Jobs");

            migrationBuilder.DropIndex(
                name: "IX_Handpieces_CreatorId",
                table: "Handpieces");

            migrationBuilder.DropColumn(
                name: "CreatorId",
                table: "Jobs");

            migrationBuilder.DropColumn(
                name: "CreatorId",
                table: "Handpieces");
        }
    }
}
