// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddUploadedImages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "UploadedImages",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    OriginalName = table.Column<string>(maxLength: 256, nullable: false),
                    Configuration = table.Column<string>(maxLength: 100, nullable: false),
                    ConfigurationVersion = table.Column<int>(nullable: false),
                    Container = table.Column<string>(maxLength: 100, nullable: false),
                    ContainerPrefix = table.Column<string>(maxLength: 100, nullable: false),
                    ReferenceCount = table.Column<int>(nullable: false),
                    ReferenceCountLastUpdated = table.Column<DateTime>(nullable: false),
                    Variations = table.Column<string>(nullable: true),
                    CustomData = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UploadedImages", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UploadedImages");
        }
    }
}
