// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddRepairedByToHandpieces : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "RepairedById",
                table: "Handpieces",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Handpieces_RepairedById",
                table: "Handpieces",
                column: "RepairedById");

            migrationBuilder.AddForeignKey(
                name: "FK_Handpieces_Employees_RepairedById",
                table: "Handpieces",
                column: "RepairedById",
                principalTable: "Employees",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Handpieces_Employees_RepairedById",
                table: "Handpieces");

            migrationBuilder.DropIndex(
                name: "IX_Handpieces_RepairedById",
                table: "Handpieces");

            migrationBuilder.DropColumn(
                name: "RepairedById",
                table: "Handpieces");
        }
    }
}
