// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddClientNoToClients : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "ClientNo",
                table: "Clients",
                nullable: true);

            migrationBuilder.Sql(@"
declare @counter int = 0
update [Clients] set @counter = @counter + 1, [ClientNo] = @counter", suppressTransaction: true);

            migrationBuilder.AlterColumn<int>(
                name: "ClientNo",
                table: "Clients",
                nullable: false);

            migrationBuilder.CreateIndex(
                name: "IX_Clients_ClientNo",
                table: "Clients",
                column: "ClientNo",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Clients_ClientNo",
                table: "Clients");

            migrationBuilder.DropColumn(
                name: "ClientNo",
                table: "Clients");
        }
    }
}
