// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class CreateCorporates : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "CorporateId",
                table: "Clients",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "Corporates",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Name = table.Column<string>(maxLength: 100, nullable: false),
                    UserId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Corporates", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Corporates_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Clients_CorporateId",
                table: "Clients",
                column: "CorporateId");

            migrationBuilder.CreateIndex(
                name: "IX_Corporates_UserId",
                table: "Corporates",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_Clients_Corporates_CorporateId",
                table: "Clients",
                column: "CorporateId",
                principalTable: "Corporates",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Clients_Corporates_CorporateId",
                table: "Clients");

            migrationBuilder.DropTable(
                name: "Corporates");

            migrationBuilder.DropIndex(
                name: "IX_Clients_CorporateId",
                table: "Clients");

            migrationBuilder.DropColumn(
                name: "CorporateId",
                table: "Clients");
        }
    }
}
