// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class UpdateHandpieceServiceLevel : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Handpieces_ServiceLevels_ServiceLevelId",
                table: "Handpieces");

            migrationBuilder.AlterColumn<Guid>(
                name: "ServiceLevelId",
                table: "Handpieces",
                nullable: true,
                oldClrType: typeof(Guid));

            migrationBuilder.AddForeignKey(
                name: "FK_Handpieces_ServiceLevels_ServiceLevelId",
                table: "Handpieces",
                column: "ServiceLevelId",
                principalTable: "ServiceLevels",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Handpieces_ServiceLevels_ServiceLevelId",
                table: "Handpieces");

            migrationBuilder.AlterColumn<Guid>(
                name: "ServiceLevelId",
                table: "Handpieces",
                nullable: false,
                oldClrType: typeof(Guid),
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Handpieces_ServiceLevels_ServiceLevelId",
                table: "Handpieces",
                column: "ServiceLevelId",
                principalTable: "ServiceLevels",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
