// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddNotificationRelatedEntities : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "NotificationRelatedEntity",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    NotificationId = table.Column<Guid>(nullable: false),
                    EntityType = table.Column<int>(nullable: false),
                    EntityId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NotificationRelatedEntity", x => x.Id);
                    table.ForeignKey(
                        name: "FK_NotificationRelatedEntity_Notifications_NotificationId",
                        column: x => x.NotificationId,
                        principalTable: "Notifications",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_NotificationRelatedEntity_NotificationId",
                table: "NotificationRelatedEntity",
                column: "NotificationId");

            migrationBuilder.CreateIndex(
                name: "IX_NotificationRelatedEntity_EntityType_EntityId",
                table: "NotificationRelatedEntity",
                columns: new[] { "EntityType", "EntityId" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "NotificationRelatedEntity");
        }
    }
}
