// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddApprovalAndRatePlanToJobs : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ApprovedBy",
                table: "Jobs",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ApprovedOn",
                table: "Jobs",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "RatePlan",
                table: "Jobs",
                nullable: false,
                defaultValue: 0);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ApprovedBy",
                table: "Jobs");

            migrationBuilder.DropColumn(
                name: "ApprovedOn",
                table: "Jobs");

            migrationBuilder.DropColumn(
                name: "RatePlan",
                table: "Jobs");
        }
    }
}
