// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class RenameTechnicianToEstimatedByInHandpieces : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Handpieces_Employees_TechnicianId",
                table: "Handpieces");

            migrationBuilder.RenameColumn(
                name: "TechnicianId",
                table: "Handpieces",
                newName: "EstimatedById");

            migrationBuilder.RenameIndex(
                name: "IX_Handpieces_TechnicianId",
                table: "Handpieces",
                newName: "IX_Handpieces_EstimatedById");

            migrationBuilder.AddForeignKey(
                name: "FK_Handpieces_Employees_EstimatedById",
                table: "Handpieces",
                column: "EstimatedById",
                principalTable: "Employees",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Handpieces_Employees_EstimatedById",
                table: "Handpieces");

            migrationBuilder.RenameColumn(
                name: "EstimatedById",
                table: "Handpieces",
                newName: "TechnicianId");

            migrationBuilder.RenameIndex(
                name: "IX_Handpieces_EstimatedById",
                table: "Handpieces",
                newName: "IX_Handpieces_TechnicianId");

            migrationBuilder.AddForeignKey(
                name: "FK_Handpieces_Employees_TechnicianId",
                table: "Handpieces",
                column: "TechnicianId",
                principalTable: "Employees",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
