// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddMultipleTypesForDiagnosticCheckItem : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "DiagnosticCheckItemTypes",
                columns: table => new
                {
                    ItemId = table.Column<Guid>(nullable: false),
                    TypeId = table.Column<Guid>(nullable: false),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DiagnosticCheckItemTypes", x => new { x.ItemId, x.TypeId });
                    table.ForeignKey(
                        name: "FK_DiagnosticCheckItemTypes_DiagnosticCheckItems_ItemId",
                        column: x => x.ItemId,
                        principalTable: "DiagnosticCheckItems",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_DiagnosticCheckItemTypes_DiagnosticCheckTypes_TypeId",
                        column: x => x.TypeId,
                        principalTable: "DiagnosticCheckTypes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_DiagnosticCheckItemTypes_TypeId",
                table: "DiagnosticCheckItemTypes",
                column: "TypeId");

            migrationBuilder.Sql(
                @"insert into [DiagnosticCheckItemTypes]
                  ([ItemId], [TypeId])
                  select [Id], [TypeId] from [DiagnosticCheckItems]",
                suppressTransaction: true);

            migrationBuilder.DropForeignKey(
                name: "FK_DiagnosticCheckItems_DiagnosticCheckTypes_TypeId",
                table: "DiagnosticCheckItems");

            migrationBuilder.DropIndex(
                name: "IX_DiagnosticCheckItems_TypeId",
                table: "DiagnosticCheckItems");

            migrationBuilder.DropColumn(
                name: "TypeId",
                table: "DiagnosticCheckItems");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "TypeId",
                table: "DiagnosticCheckItems",
                nullable: true);

            migrationBuilder.Sql(
                @"update [DiagnosticCheckItems]
                  set [TypeId] = q.[FirstTypeId]
                  from [DiagnosticCheckItems] inner join (
                      select [DiagnosticCheckItems].[Id], min([DiagnosticCheckItemTypes].[TypeId]) as [FirstTypeId]
                      from [DiagnosticCheckItems]
                      inner join [DiagnosticCheckItemTypes] on [DiagnosticCheckItems].[Id] = [DiagnosticCheckItemTypes].[ItemId]
                      group by [DiagnosticCheckItems].[Id]
                  ) q on q.[Id] = [DiagnosticCheckItems].[Id]

                  if (exists(select 1 from [DiagnosticCheckItems] where [TypeId] is null)) begin
	                  declare @defaultId uniqueidentifier
	                  select top 1 @defaultId = [Id] from [DiagnosticCheckTypes] where [Name] = 'Default' order by [OrderNo]
	                  if @@rowcount = 0 begin
		                  select top 1 @defaultId = [Id] from [DiagnosticCheckTypes] order by [OrderNo]
		                  if @@rowcount = 0 begin
		                      set @defaultId = newid()
			                  insert into [DiagnosticCheckTypes] ([Id], [Name], [OrderNo]) values (@defaultId, 'Default', 1)
		                  end
	                  end
	                    
	                  update [DiagnosticCheckItems] set [TypeId] = @defaultId where [TypeId] is null
                  end",
                suppressTransaction: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "TypeId",
                table: "DiagnosticCheckItems",
                nullable: false);

            migrationBuilder.CreateIndex(
                name: "IX_DiagnosticCheckItems_TypeId",
                table: "DiagnosticCheckItems",
                column: "TypeId");

            migrationBuilder.AddForeignKey(
                name: "FK_DiagnosticCheckItems_DiagnosticCheckTypes_TypeId",
                table: "DiagnosticCheckItems",
                column: "TypeId",
                principalTable: "DiagnosticCheckTypes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.DropTable(
                name: "DiagnosticCheckItemTypes");
        }
    }
}
