// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHandpieceModelSchematics : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HandpieceModelSchematics",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    ModelId = table.Column<Guid>(nullable: false),
                    OrderNo = table.Column<int>(nullable: false),
                    Title = table.Column<string>(maxLength: 200, nullable: true),
                    Display = table.Column<bool>(nullable: false),
                    Type = table.Column<int>(nullable: false),
                    Text = table.Column<string>(nullable: true),
                    AttachmentId = table.Column<Guid>(nullable: true),
                    ImageId = table.Column<Guid>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceModelSchematics", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HandpieceModelSchematics_UploadedFiles_AttachmentId",
                        column: x => x.AttachmentId,
                        principalTable: "UploadedFiles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_HandpieceModelSchematics_UploadedImages_ImageId",
                        column: x => x.ImageId,
                        principalTable: "UploadedImages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_HandpieceModelSchematics_HandpieceModels_ModelId",
                        column: x => x.ModelId,
                        principalTable: "HandpieceModels",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceModelSchematics_AttachmentId",
                table: "HandpieceModelSchematics",
                column: "AttachmentId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceModelSchematics_ImageId",
                table: "HandpieceModelSchematics",
                column: "ImageId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceModelSchematics_ModelId_OrderNo",
                table: "HandpieceModelSchematics",
                columns: new[] { "ModelId", "OrderNo" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HandpieceModelSchematics");
        }
    }
}
