// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddDiagnosticCheckTypes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "DiagnosticCheckTypes",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Name = table.Column<string>(maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DiagnosticCheckTypes", x => x.Id);
                });

            migrationBuilder.AddColumn<Guid>(
                name: "TypeId",
                table: "DiagnosticCheckItems",
                nullable: true);

            migrationBuilder.Sql(@"
declare @typeId uniqueidentifier = newid()
insert into [DiagnosticCheckTypes] ([Id], [Name]) values (@typeId, 'Default')
update [DiagnosticCheckItems] set [TypeId] = @typeId", suppressTransaction: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "TypeId",
                table: "DiagnosticCheckItems",
                nullable: false);

            migrationBuilder.CreateIndex(
                name: "IX_DiagnosticCheckItems_TypeId",
                table: "DiagnosticCheckItems",
                column: "TypeId");

            migrationBuilder.AddForeignKey(
                name: "FK_DiagnosticCheckItems_DiagnosticCheckTypes_TypeId",
                table: "DiagnosticCheckItems",
                column: "TypeId",
                principalTable: "DiagnosticCheckTypes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_DiagnosticCheckItems_DiagnosticCheckTypes_TypeId",
                table: "DiagnosticCheckItems");

            migrationBuilder.DropTable(
                name: "DiagnosticCheckTypes");

            migrationBuilder.DropIndex(
                name: "IX_DiagnosticCheckItems_TypeId",
                table: "DiagnosticCheckItems");

            migrationBuilder.DropColumn(
                name: "TypeId",
                table: "DiagnosticCheckItems");
        }
    }
}
