// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddStockControlEntries : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "StockControlEntries",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    CompletedAt = table.Column<DateTimeOffset>(nullable: false),
                    HandpieceId = table.Column<Guid>(nullable: false),
                    WeekId = table.Column<Guid>(nullable: false),
                    Status = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StockControlEntries", x => x.Id);
                    table.ForeignKey(
                        name: "FK_StockControlEntries_Handpieces_HandpieceId",
                        column: x => x.HandpieceId,
                        principalTable: "Handpieces",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_StockControlEntries_CalendarWeeks_WeekId",
                        column: x => x.WeekId,
                        principalTable: "CalendarWeeks",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_StockControlEntries_HandpieceId",
                table: "StockControlEntries",
                column: "HandpieceId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_StockControlEntries_WeekId",
                table: "StockControlEntries",
                column: "WeekId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "StockControlEntries");
        }
    }
}
