// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHandpieceChanges : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HandpieceChanges",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    HandpieceId = table.Column<Guid>(nullable: false),
                    ChangedOn = table.Column<DateTime>(nullable: false),
                    ChangedById = table.Column<Guid>(nullable: false),
                    Action = table.Column<int>(nullable: false),
                    OldStatus = table.Column<int>(nullable: true),
                    NewStatus = table.Column<int>(nullable: true),
                    OldContent = table.Column<string>(nullable: true),
                    NewContent = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceChanges", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HandpieceChanges_Employees_ChangedById",
                        column: x => x.ChangedById,
                        principalTable: "Employees",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_HandpieceChanges_Handpieces_HandpieceId",
                        column: x => x.HandpieceId,
                        principalTable: "Handpieces",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceChanges_ChangedById",
                table: "HandpieceChanges",
                column: "ChangedById");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceChanges_HandpieceId",
                table: "HandpieceChanges",
                column: "HandpieceId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HandpieceChanges");
        }
    }
}
