// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddAppearanceBackgroundAndOpacityToEmployees : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "AppearanceBackgroundId",
                table: "Employees",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "AppearanceOpacity",
                table: "Employees",
                type: "decimal(9,4)",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Employees_AppearanceBackgroundId",
                table: "Employees",
                column: "AppearanceBackgroundId");

            migrationBuilder.AddForeignKey(
                name: "FK_Employees_UploadedFiles_AppearanceBackgroundId",
                table: "Employees",
                column: "AppearanceBackgroundId",
                principalTable: "UploadedFiles",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Employees_UploadedFiles_AppearanceBackgroundId",
                table: "Employees");

            migrationBuilder.DropIndex(
                name: "IX_Employees_AppearanceBackgroundId",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "AppearanceBackgroundId",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "AppearanceOpacity",
                table: "Employees");
        }
    }
}
