// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddPartsDetailsToHandpiece : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "PartsComment",
                table: "Handpieces",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "PartsOrdered",
                table: "Handpieces",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "PartsRestocked",
                table: "Handpieces",
                nullable: true);

            migrationBuilder.Sql(
                @"update [Handpieces] set [PartsOrdered] = 0, [PartsRestocked] = 0",
                suppressTransaction: true);

            migrationBuilder.Sql(
                @"update [Handpieces] set [PartsRestocked] = 1 from [Handpieces] inner join (select [HandpieceId], [Status] from [StockControlEntries] where [Status] = 2) q on [Id] = q.[HandpieceId]",
                suppressTransaction: true);

            migrationBuilder.AlterColumn<bool>(
                name: "PartsOrdered",
                table: "Handpieces",
                nullable: true);

            migrationBuilder.AlterColumn<bool>(
                name: "PartsRestocked",
                table: "Handpieces",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "PartsComment",
                table: "Handpieces");

            migrationBuilder.DropColumn(
                name: "PartsOrdered",
                table: "Handpieces");

            migrationBuilder.DropColumn(
                name: "PartsRestocked",
                table: "Handpieces");
        }
    }
}
