// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddLoggedEvents : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "LoggedEvents",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Timestamp = table.Column<DateTime>(nullable: false),
                    RequestHost = table.Column<string>(maxLength: 300, nullable: true),
                    RequestMethod = table.Column<string>(maxLength: 10, nullable: false),
                    RequestAddress = table.Column<string>(maxLength: 1024, nullable: false),
                    UserName = table.Column<string>(maxLength: 256, nullable: true),
                    UserAddress = table.Column<string>(maxLength: 40, nullable: false),
                    UserAgent = table.Column<string>(maxLength: 512, nullable: true),
                    RequestId = table.Column<string>(maxLength: 1024, nullable: false),
                    Category = table.Column<string>(maxLength: 512, nullable: true),
                    LogLevel = table.Column<string>(maxLength: 5, nullable: true),
                    EventId = table.Column<int>(nullable: false),
                    EventName = table.Column<string>(maxLength: 256, nullable: true),
                    EventScope = table.Column<string>(nullable: true),
                    EventMessage = table.Column<string>(nullable: true),
                    ExceptionClass = table.Column<string>(nullable: true),
                    ExceptionMessage = table.Column<string>(nullable: true),
                    ExceptionDetails = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LoggedEvents", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "LoggedEvents");
        }
    }
}
