// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddPickupRequestAnonymousRecipients : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PickupRequestAnonymousRecipients",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    AccountNumber = table.Column<int>(nullable: false),
                    UniqueKey = table.Column<string>(maxLength: 300, nullable: false),
                    PracticeName = table.Column<string>(maxLength: 100, nullable: false),
                    AddressLine1 = table.Column<string>(maxLength: 30, nullable: false),
                    AddressLine2 = table.Column<string>(maxLength: 30, nullable: true),
                    Suburb = table.Column<string>(maxLength: 50, nullable: false),
                    State = table.Column<string>(maxLength: 25, nullable: false),
                    Postcode = table.Column<string>(maxLength: 10, nullable: false),
                    Country = table.Column<string>(maxLength: 30, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PickupRequestAnonymousRecipients", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PickupRequestAnonymousRecipients_AccountNumber",
                table: "PickupRequestAnonymousRecipients",
                column: "AccountNumber",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_PickupRequestAnonymousRecipients_UniqueKey",
                table: "PickupRequestAnonymousRecipients",
                column: "UniqueKey",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PickupRequestAnonymousRecipients");
        }
    }
}
