// <auto-generated />
using System;
using DentalDrill.CRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DentalDrill.CRM.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190915101943_AddHandpieceModelSchematics")]
    partial class AddHandpieceModelSchematics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DentalDrill.CRM.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<bool>("MustChangePasswordAtNextLogin");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.CalendarWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("RangeEnd");

                    b.Property<DateTimeOffset>("RangeStart");

                    b.Property<int>("Week");

                    b.Property<Guid>("YearId");

                    b.HasKey("Id");

                    b.HasIndex("YearId", "Week")
                        .IsUnique();

                    b.ToTable("CalendarWeeks");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.CalendarYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("RangeEnd");

                    b.Property<DateTimeOffset>("RangeStart");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("CalendarYears");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(200);

                    b.Property<string>("Brands");

                    b.Property<int>("ClientNo");

                    b.Property<string>("Comment");

                    b.Property<Guid?>("CorporateId");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailsEnabled");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("ImportKey")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(100);

                    b.Property<string>("OtherContact")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<string>("PostCode")
                        .HasMaxLength(4);

                    b.Property<string>("PrincipalDentist")
                        .HasMaxLength(100);

                    b.Property<string>("SecondaryEmails");

                    b.Property<string>("SecondaryPhones");

                    b.Property<Guid>("StateId");

                    b.Property<string>("Suburb")
                        .HasMaxLength(200);

                    b.Property<string>("UrlPath")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid?>("UserId");

                    b.Property<Guid>("ZoneId");

                    b.HasKey("Id");

                    b.HasIndex("ClientNo")
                        .IsUnique();

                    b.HasIndex("CorporateId");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("StateId");

                    b.HasIndex("UrlPath")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientAppearance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BackgroundImageId");

                    b.Property<Guid>("ClientId");

                    b.Property<string>("HeaderTextColor");

                    b.Property<Guid?>("LogoId");

                    b.Property<string>("PrimaryColor");

                    b.Property<string>("SecondaryColor");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundImageId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("LogoId");

                    b.ToTable("ClientAppearances");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClientId");

                    b.Property<string>("Comment");

                    b.Property<Guid>("EmployeeId");

                    b.Property<Guid>("FileId");

                    b.Property<DateTime>("UploadedOn");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FileId");

                    b.ToTable("ClientAttachments");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientCallbackNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AssignedToId");

                    b.Property<DateTime?>("CallDateTime");

                    b.Property<Guid>("ClientId");

                    b.Property<DateTime?>("CompletedOn");

                    b.Property<Guid>("CreatedById");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Note");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedById");

                    b.ToTable("ClientCallbackNotifications");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientEmailMessage", b =>
                {
                    b.Property<Guid>("ClientId");

                    b.Property<int>("EmailMessageId");

                    b.HasKey("ClientId", "EmailMessageId");

                    b.HasIndex("EmailMessageId");

                    b.ToTable("ClientEmailMessage");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClientId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatorId");

                    b.ToTable("ClientNotes");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Corporate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CorporateNo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UrlPath")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CorporateNo")
                        .IsUnique();

                    b.HasIndex("UrlPath")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Corporates");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.CorporateAppearance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BackgroundImageId");

                    b.Property<Guid>("CorporateId");

                    b.Property<string>("HeaderTextColor");

                    b.Property<Guid?>("LogoId");

                    b.Property<string>("PrimaryColor");

                    b.Property<string>("SecondaryColor");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundImageId");

                    b.HasIndex("CorporateId")
                        .IsUnique();

                    b.HasIndex("LogoId");

                    b.ToTable("CorporateAppearances");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.DiagnosticCheckItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("DiagnosticCheckItems");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.DiagnosticCheckItemType", b =>
                {
                    b.Property<Guid>("ItemId");

                    b.Property<Guid>("TypeId");

                    b.HasKey("ItemId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("DiagnosticCheckItemTypes");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.DiagnosticCheckType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("OrderNo");

                    b.HasKey("Id");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.ToTable("DiagnosticCheckTypes");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppearanceTheme");

                    b.Property<Guid>("ApplicationUserId");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Handpiece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CompletedOn");

                    b.Property<decimal>("CostOfRepair")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("DiagnosticOther");

                    b.Property<string>("DiagnosticReport");

                    b.Property<Guid?>("EstimatedById");

                    b.Property<int>("HandpieceStatus");

                    b.Property<string>("ImportKey")
                        .HasMaxLength(200);

                    b.Property<string>("InternalComment");

                    b.Property<Guid>("JobId");

                    b.Property<int>("JobPosition");

                    b.Property<string>("MakeAndModel")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("OldMakeAndModel")
                        .HasMaxLength(200);

                    b.Property<string>("Parts")
                        .HasMaxLength(200);

                    b.Property<string>("PartsComment");

                    b.Property<bool>("PartsOrdered");

                    b.Property<bool>("PartsOutOfStock");

                    b.Property<bool>("PartsRestocked");

                    b.Property<string>("ProblemDescription");

                    b.Property<string>("PublicComment");

                    b.Property<int>("Rating");

                    b.Property<Guid?>("RepairedById");

                    b.Property<Guid?>("ReturnById");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid?>("ServiceLevelId");

                    b.Property<int>("Speed");

                    b.Property<int>("SpeedType");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EstimatedById");

                    b.HasIndex("MakeAndModel");

                    b.HasIndex("RepairedById");

                    b.HasIndex("ReturnById");

                    b.HasIndex("ServiceLevelId");

                    b.HasIndex("JobId", "JobPosition")
                        .IsUnique();

                    b.ToTable("Handpieces");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ImageId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("HandpieceBrands");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Action");

                    b.Property<Guid>("ChangedById");

                    b.Property<DateTime>("ChangedOn");

                    b.Property<Guid>("HandpieceId");

                    b.Property<string>("NewContent");

                    b.Property<int?>("NewStatus");

                    b.Property<string>("OldContent");

                    b.Property<int?>("OldStatus");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("HandpieceId");

                    b.ToTable("HandpieceChanges");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceDiagnostic", b =>
                {
                    b.Property<Guid>("HandpieceId");

                    b.Property<Guid>("ItemId");

                    b.Property<Guid>("Id");

                    b.HasKey("HandpieceId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("HandpieceDiagnostics");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<bool>("Display");

                    b.Property<Guid>("HandpieceId");

                    b.Property<Guid>("ImageId");

                    b.HasKey("Id");

                    b.HasIndex("HandpieceId");

                    b.HasIndex("ImageId");

                    b.ToTable("HandpieceImages");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BrandId");

                    b.Property<string>("Description");

                    b.Property<Guid?>("ImageId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Type");

                    b.Property<string>("WorkshopNotes");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("BrandId", "Name")
                        .IsUnique();

                    b.HasIndex("BrandId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("HandpieceModels");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceModelSchematic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AttachmentId");

                    b.Property<bool>("Display");

                    b.Property<Guid?>("ImageId");

                    b.Property<Guid>("ModelId");

                    b.Property<int>("OrderNo");

                    b.Property<string>("Text");

                    b.Property<string>("Title")
                        .HasMaxLength(200);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ImageId");

                    b.HasIndex("ModelId", "OrderNo")
                        .IsUnique();

                    b.ToTable("HandpieceModelSchematics");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedOn");

                    b.Property<Guid>("ClientId");

                    b.Property<string>("Comment");

                    b.Property<Guid>("CreatorId");

                    b.Property<bool>("HasWarning");

                    b.Property<long>("JobNumber");

                    b.Property<int>("RatePlan");

                    b.Property<DateTime>("Received")
                        .HasColumnType("date");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("JobNumber")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.JobChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Action");

                    b.Property<Guid>("ChangedById");

                    b.Property<DateTime>("ChangedOn");

                    b.Property<Guid>("JobId");

                    b.Property<string>("NewContent");

                    b.Property<int?>("NewStatus");

                    b.Property<string>("OldContent");

                    b.Property<int?>("OldStatus");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("JobId");

                    b.ToTable("JobChanges");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.JobInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("EmployeeId");

                    b.Property<Guid>("FileId");

                    b.Property<int>("InvoiceNumber");

                    b.Property<Guid>("JobId");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FileId");

                    b.HasIndex("JobId", "InvoiceNumber")
                        .IsUnique();

                    b.ToTable("JobInvoices");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Payload");

                    b.Property<DateTime?>("ReadOn");

                    b.Property<Guid?>("RecipientId");

                    b.Property<DateTime?>("ResolvedOn");

                    b.Property<int>("Scope");

                    b.Property<int>("Status");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.NotificationRelatedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EntityId");

                    b.Property<int>("EntityType");

                    b.Property<Guid>("NotificationId");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId", "EntityType", "EntityId")
                        .IsUnique();

                    b.ToTable("NotificationRelatedEntity");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.PickupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(30);

                    b.Property<Guid?>("ClientId");

                    b.Property<string>("Comment")
                        .HasMaxLength(90);

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid?>("CorporateId");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<Guid?>("CreatedById");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<Guid?>("EmployeeId");

                    b.Property<int>("HandpiecesCount");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("PracticeName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("Status");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CorporateId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PickupRequests");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.PickupRequestAnonymousRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountNumber");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(30);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("PracticeName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("UniqueKey")
                        .IsUnique();

                    b.ToTable("PickupRequestAnonymousRecipients");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.PickupRequestConsignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("ExceptionClass");

                    b.Property<string>("ExceptionDetails");

                    b.Property<string>("ExceptionMessage");

                    b.Property<string>("Reference");

                    b.Property<Guid>("RequestId");

                    b.Property<string>("RequestXml");

                    b.Property<string>("ResponseXml");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("PickupRequestConsignments");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ProblemDescriptionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ProblemDescriptionOptions");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ReturnEstimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ReturnEstimates");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ServiceLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ServiceLevels");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.StockControlEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CompletedAt");

                    b.Property<Guid>("HandpieceId");

                    b.Property<int>("Status");

                    b.Property<Guid>("WeekId");

                    b.HasKey("Id");

                    b.HasIndex("HandpieceId")
                        .IsUnique();

                    b.HasIndex("WeekId");

                    b.ToTable("StockControlEntries");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("DevGuild.AspNetCore.Services.EntitySequences.EntitySequence", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<long>("NextSequenceId");

                    b.HasKey("Id");

                    b.ToTable("EntitySequences");
                });

            modelBuilder.Entity("DevGuild.AspNetCore.Services.Identity.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DevGuild.AspNetCore.Services.Logging.Data.LoggedEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasMaxLength(512);

                    b.Property<int>("EventId");

                    b.Property<string>("EventMessage");

                    b.Property<string>("EventName")
                        .HasMaxLength(256);

                    b.Property<string>("EventScope");

                    b.Property<string>("ExceptionClass");

                    b.Property<string>("ExceptionDetails");

                    b.Property<string>("ExceptionMessage");

                    b.Property<string>("LogLevel")
                        .HasMaxLength(5);

                    b.Property<string>("RequestAddress")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("RequestHost")
                        .HasMaxLength(300);

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("UserAddress")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512);

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("LoggedEvents");
                });

            modelBuilder.Entity("DevGuild.AspNetCore.Services.Mail.Models.EmailMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bcc");

                    b.Property<string>("Cc");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Content");

                    b.Property<DateTime>("Created");

                    b.Property<string>("From");

                    b.Property<string>("MessageId");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("SendingError");

                    b.Property<int>("Status");

                    b.Property<string>("Subject");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("DevGuild.AspNetCore.Services.Uploads.Files.Models.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("ConfigurationVersion");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ContainerPrefix")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("Created");

                    b.Property<string>("CustomDataContent")
                        .HasColumnName("CustomData");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(88);

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("ReferenceCount");

                    b.Property<DateTime>("ReferenceCountLastUpdated");

                    b.Property<long>("Size");

                    b.HasKey("Id");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("DevGuild.AspNetCore.Services.Uploads.Images.Models.UploadedImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("ConfigurationVersion");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ContainerPrefix")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("CustomDataContent")
                        .HasColumnName("CustomData");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("ReferenceCount");

                    b.Property<DateTime>("ReferenceCountLastUpdated");

                    b.Property<string>("VariationsContent")
                        .HasColumnName("Variations");

                    b.HasKey("Id");

                    b.ToTable("UploadedImages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.CalendarWeek", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.CalendarYear", "Year")
                        .WithMany()
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Client", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Corporate", "Corporate")
                        .WithMany("Clients")
                        .HasForeignKey("CorporateId");

                    b.HasOne("DentalDrill.CRM.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("DentalDrill.CRM.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientAppearance", b =>
                {
                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Images.Models.UploadedImage", "BackgroundImage")
                        .WithMany()
                        .HasForeignKey("BackgroundImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DentalDrill.CRM.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Images.Models.UploadedImage", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientAttachment", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Client", "Client")
                        .WithMany("Attachments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Files.Models.UploadedFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientCallbackNotification", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Employee", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DentalDrill.CRM.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.Employee", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientEmailMessage", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevGuild.AspNetCore.Services.Mail.Models.EmailMessage", "EmailMessage")
                        .WithMany()
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.ClientNote", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Client", "Client")
                        .WithMany("Notes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.Employee", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Corporate", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.CorporateAppearance", b =>
                {
                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Images.Models.UploadedImage", "BackgroundImage")
                        .WithMany()
                        .HasForeignKey("BackgroundImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DentalDrill.CRM.Models.Corporate", "Corporate")
                        .WithMany()
                        .HasForeignKey("CorporateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Images.Models.UploadedImage", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.DiagnosticCheckItemType", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.DiagnosticCheckItem", "Item")
                        .WithMany("Types")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.DiagnosticCheckType", "Type")
                        .WithMany("Items")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Employee", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Handpiece", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Employee", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DentalDrill.CRM.Models.Employee", "EstimatedBy")
                        .WithMany()
                        .HasForeignKey("EstimatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DentalDrill.CRM.Models.Job", "Job")
                        .WithMany("Handpieces")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.Employee", "RepairedBy")
                        .WithMany()
                        .HasForeignKey("RepairedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DentalDrill.CRM.Models.ReturnEstimate", "ReturnBy")
                        .WithMany()
                        .HasForeignKey("ReturnById");

                    b.HasOne("DentalDrill.CRM.Models.ServiceLevel", "ServiceLevel")
                        .WithMany()
                        .HasForeignKey("ServiceLevelId");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceBrand", b =>
                {
                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Images.Models.UploadedImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceChange", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Employee", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DentalDrill.CRM.Models.Handpiece", "Handpiece")
                        .WithMany("Changes")
                        .HasForeignKey("HandpieceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceDiagnostic", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Handpiece", "Handpiece")
                        .WithMany("SelectedDiagnosticCheckItems")
                        .HasForeignKey("HandpieceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.DiagnosticCheckItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceImage", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Handpiece", "Handpiece")
                        .WithMany("Images")
                        .HasForeignKey("HandpieceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Images.Models.UploadedImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceModel", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.HandpieceBrand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Images.Models.UploadedImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.HandpieceModelSchematic", b =>
                {
                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Files.Models.UploadedFile", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Images.Models.UploadedImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("DentalDrill.CRM.Models.HandpieceModel", "Model")
                        .WithMany("Schematics")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Job", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Client", "Client")
                        .WithMany("Jobs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.Employee", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.JobChange", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Employee", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DentalDrill.CRM.Models.Job", "Job")
                        .WithMany("Changes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.JobInvoice", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevGuild.AspNetCore.Services.Uploads.Files.Models.UploadedFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.Job", "Job")
                        .WithMany("Invoices")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.Notification", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Employee", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.NotificationRelatedEntity", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Notification", "Notification")
                        .WithMany("RelatedEntities")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.PickupRequest", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("DentalDrill.CRM.Models.Corporate", "Corporate")
                        .WithMany()
                        .HasForeignKey("CorporateId");

                    b.HasOne("DentalDrill.CRM.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DentalDrill.CRM.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.PickupRequestConsignment", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.PickupRequest", "Request")
                        .WithMany("Consignments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DentalDrill.CRM.Models.StockControlEntry", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.Handpiece", "Handpiece")
                        .WithMany()
                        .HasForeignKey("HandpieceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.CalendarWeek", "Week")
                        .WithMany()
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("DevGuild.AspNetCore.Services.Identity.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("DevGuild.AspNetCore.Services.Identity.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentalDrill.CRM.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DentalDrill.CRM.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
