// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddPickupRequests : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PickupRequests",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    CreatedOn = table.Column<DateTime>(nullable: false),
                    CreatedById = table.Column<Guid>(nullable: true),
                    EmployeeId = table.Column<Guid>(nullable: true),
                    ClientId = table.Column<Guid>(nullable: true),
                    CorporateId = table.Column<Guid>(nullable: true),
                    Type = table.Column<int>(nullable: false),
                    Status = table.Column<int>(nullable: false),
                    PracticeName = table.Column<string>(maxLength: 100, nullable: false),
                    ContactPerson = table.Column<string>(maxLength: 100, nullable: false),
                    Email = table.Column<string>(maxLength: 256, nullable: false),
                    Phone = table.Column<string>(maxLength: 20, nullable: false),
                    AddressLine1 = table.Column<string>(maxLength: 30, nullable: false),
                    AddressLine2 = table.Column<string>(maxLength: 30, nullable: true),
                    Suburb = table.Column<string>(maxLength: 50, nullable: false),
                    State = table.Column<string>(maxLength: 25, nullable: false),
                    Postcode = table.Column<string>(maxLength: 10, nullable: false),
                    Country = table.Column<string>(maxLength: 30, nullable: false),
                    HandpiecesCount = table.Column<int>(nullable: false),
                    Comment = table.Column<string>(maxLength: 90, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PickupRequests", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PickupRequests_Clients_ClientId",
                        column: x => x.ClientId,
                        principalTable: "Clients",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_PickupRequests_Corporates_CorporateId",
                        column: x => x.CorporateId,
                        principalTable: "Corporates",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_PickupRequests_Users_CreatedById",
                        column: x => x.CreatedById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_PickupRequests_Employees_EmployeeId",
                        column: x => x.EmployeeId,
                        principalTable: "Employees",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PickupRequests_ClientId",
                table: "PickupRequests",
                column: "ClientId");

            migrationBuilder.CreateIndex(
                name: "IX_PickupRequests_CorporateId",
                table: "PickupRequests",
                column: "CorporateId");

            migrationBuilder.CreateIndex(
                name: "IX_PickupRequests_CreatedById",
                table: "PickupRequests",
                column: "CreatedById");

            migrationBuilder.CreateIndex(
                name: "IX_PickupRequests_EmployeeId",
                table: "PickupRequests",
                column: "EmployeeId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PickupRequests");
        }
    }
}
