// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHandpieceModels : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HandpieceModels",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    BrandId = table.Column<Guid>(nullable: false),
                    Name = table.Column<string>(maxLength: 200, nullable: false),
                    NormalizedName = table.Column<string>(maxLength: 200, nullable: false),
                    Type = table.Column<int>(nullable: false),
                    ImageId = table.Column<Guid>(nullable: true),
                    Description = table.Column<string>(nullable: true),
                    WorkshopNotes = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceModels", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HandpieceModels_HandpieceBrands_BrandId",
                        column: x => x.BrandId,
                        principalTable: "HandpieceBrands",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_HandpieceModels_UploadedImages_ImageId",
                        column: x => x.ImageId,
                        principalTable: "UploadedImages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceModels_ImageId",
                table: "HandpieceModels",
                column: "ImageId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceModels_BrandId_Name",
                table: "HandpieceModels",
                columns: new[] { "BrandId", "Name" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceModels_BrandId_NormalizedName",
                table: "HandpieceModels",
                columns: new[] { "BrandId", "NormalizedName" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HandpieceModels");
        }
    }
}
