// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddOrderNoToDiagnosticCheckTypes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "OrderNo",
                table: "DiagnosticCheckTypes",
                nullable: true);

            migrationBuilder.Sql(@"
declare @orderNo int = 1
update [DiagnosticCheckTypes] set [OrderNo] = @orderNo, @orderNo = @orderNo + 1", suppressTransaction: true);

            migrationBuilder.AlterColumn<int>(
                name: "OrderNo",
                table: "DiagnosticCheckTypes",
                nullable: false);

            migrationBuilder.CreateIndex(
                name: "IX_DiagnosticCheckTypes_OrderNo",
                table: "DiagnosticCheckTypes",
                column: "OrderNo",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_DiagnosticCheckTypes_OrderNo",
                table: "DiagnosticCheckTypes");

            migrationBuilder.DropColumn(
                name: "OrderNo",
                table: "DiagnosticCheckTypes");
        }
    }
}
