// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddCalendar : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CalendarYears",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Year = table.Column<int>(nullable: false),
                    RangeStart = table.Column<DateTimeOffset>(nullable: false),
                    RangeEnd = table.Column<DateTimeOffset>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CalendarYears", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "CalendarWeeks",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    YearId = table.Column<Guid>(nullable: false),
                    Week = table.Column<int>(nullable: false),
                    RangeStart = table.Column<DateTimeOffset>(nullable: false),
                    RangeEnd = table.Column<DateTimeOffset>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CalendarWeeks", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CalendarWeeks_CalendarYears_YearId",
                        column: x => x.YearId,
                        principalTable: "CalendarYears",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CalendarWeeks_YearId_Week",
                table: "CalendarWeeks",
                columns: new[] { "YearId", "Week" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_CalendarYears_Year",
                table: "CalendarYears",
                column: "Year",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CalendarWeeks");

            migrationBuilder.DropTable(
                name: "CalendarYears");
        }
    }
}
