// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHandpieceBrands : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HandpieceBrands",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Name = table.Column<string>(maxLength: 200, nullable: false),
                    NormalizedName = table.Column<string>(maxLength: 200, nullable: false),
                    ImageId = table.Column<Guid>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceBrands", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HandpieceBrands_UploadedImages_ImageId",
                        column: x => x.ImageId,
                        principalTable: "UploadedImages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceBrands_ImageId",
                table: "HandpieceBrands",
                column: "ImageId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceBrands_Name",
                table: "HandpieceBrands",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceBrands_NormalizedName",
                table: "HandpieceBrands",
                column: "NormalizedName",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HandpieceBrands");
        }
    }
}
