// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddFeedbackConfiguration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FeedbackConfiguration",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    AutoSendFormEnabled = table.Column<bool>(nullable: false),
                    AutoSendFormDelayDays = table.Column<int>(nullable: false),
                    AutoSendSkipJobs = table.Column<int>(nullable: false),
                    PeriodLimitingEnabled = table.Column<bool>(nullable: false),
                    PeriodLimitingType = table.Column<int>(nullable: false),
                    PeriodLimitingLength = table.Column<int>(nullable: false),
                    PeriodLimitingQuantity = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FeedbackConfiguration", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FeedbackConfiguration");
        }
    }
}
