// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHandpieceStoreOrders : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HandpieceStoreOrders",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    CreatedOn = table.Column<DateTime>(nullable: false),
                    ConfirmedOn = table.Column<DateTime>(nullable: true),
                    ShippedOn = table.Column<DateTime>(nullable: true),
                    DeliveredOn = table.Column<DateTime>(nullable: true),
                    CreatedById = table.Column<Guid>(nullable: true),
                    EmployeeId = table.Column<Guid>(nullable: true),
                    ClientId = table.Column<Guid>(nullable: true),
                    CorporateId = table.Column<Guid>(nullable: true),
                    SurgeryName = table.Column<string>(maxLength: 200, nullable: false),
                    ContactName = table.Column<string>(maxLength: 200, nullable: false),
                    ContactEmail = table.Column<string>(maxLength: 256, nullable: false),
                    Status = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceStoreOrders", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HandpieceStoreOrders_Clients_ClientId",
                        column: x => x.ClientId,
                        principalTable: "Clients",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_HandpieceStoreOrders_Corporates_CorporateId",
                        column: x => x.CorporateId,
                        principalTable: "Corporates",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_HandpieceStoreOrders_Users_CreatedById",
                        column: x => x.CreatedById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_HandpieceStoreOrders_Employees_EmployeeId",
                        column: x => x.EmployeeId,
                        principalTable: "Employees",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "HandpieceStoreOrderItems",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    OrderId = table.Column<Guid>(nullable: false),
                    ListingId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceStoreOrderItems", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HandpieceStoreOrderItems_HandpieceStoreListings_ListingId",
                        column: x => x.ListingId,
                        principalTable: "HandpieceStoreListings",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_HandpieceStoreOrderItems_HandpieceStoreOrders_OrderId",
                        column: x => x.OrderId,
                        principalTable: "HandpieceStoreOrders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreOrderItems_ListingId",
                table: "HandpieceStoreOrderItems",
                column: "ListingId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreOrderItems_OrderId",
                table: "HandpieceStoreOrderItems",
                column: "OrderId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreOrders_ClientId",
                table: "HandpieceStoreOrders",
                column: "ClientId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreOrders_CorporateId",
                table: "HandpieceStoreOrders",
                column: "CorporateId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreOrders_CreatedById",
                table: "HandpieceStoreOrders",
                column: "CreatedById");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreOrders_EmployeeId",
                table: "HandpieceStoreOrders",
                column: "EmployeeId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HandpieceStoreOrderItems");

            migrationBuilder.DropTable(
                name: "HandpieceStoreOrders");
        }
    }
}
