// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class MoveCouplingToHandpieceStoreListings : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Coupling",
                table: "HandpieceStoreListings",
                maxLength: 200,
                nullable: true);

            migrationBuilder.Sql(
                @"update [HandpieceStoreListings]
                      set [Coupling] = [HandpieceModels].[Coupling]
                  from [HandpieceStoreListings]
                  inner join [HandpieceModels] on [HandpieceStoreListings].[ModelId] = [HandpieceModels].[Id]",
                suppressTransaction: true);

            migrationBuilder.DropColumn(
                name: "Coupling",
                table: "HandpieceModels");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Coupling",
                table: "HandpieceStoreListings");

            migrationBuilder.AddColumn<string>(
                name: "Coupling",
                table: "HandpieceModels",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: true);
        }
    }
}
