// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddCreatedOnAndScheduledOnToFeedbackForms : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedOn",
                table: "FeedbackForms",
                nullable: true);

            migrationBuilder.Sql(
                @"update [FeedbackForms] set [CreatedOn] = [SentOn]",
                suppressTransaction: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "SentOn",
                table: "FeedbackForms",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "datetime2");

            migrationBuilder.AlterColumn<DateTime>(
                name: "CreatedOn",
                table: "FeedbackForms",
                type: "datetime2",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldNullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ScheduledOn",
                table: "FeedbackForms",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "CreatedOn",
                table: "FeedbackForms");

            migrationBuilder.DropColumn(
                name: "ScheduledOn",
                table: "FeedbackForms");

            migrationBuilder.Sql(
                @"update [FeedbackForms] set [SentOn] = [CreatedOn] where [SentOn] is null",
                suppressTransaction: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "SentOn",
                table: "FeedbackForms",
                type: "datetime2",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldNullable: true);
        }
    }
}
