// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHandpieceStoreListings : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HandpieceStoreListings",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    ModelId = table.Column<Guid>(nullable: false),
                    Status = table.Column<int>(nullable: false),
                    SerialNumber = table.Column<string>(maxLength: 100, nullable: true),
                    CreatedOn = table.Column<DateTime>(nullable: false),
                    RequestedOn = table.Column<DateTime>(nullable: true),
                    SoldOn = table.Column<DateTime>(nullable: true),
                    Price = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Warranty = table.Column<string>(maxLength: 200, nullable: true),
                    Notes = table.Column<string>(nullable: true),
                    CosmeticCondition = table.Column<string>(maxLength: 200, nullable: true),
                    FiberOpticBrightness = table.Column<string>(maxLength: 200, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceStoreListings", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HandpieceStoreListings_HandpieceModels_ModelId",
                        column: x => x.ModelId,
                        principalTable: "HandpieceModels",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreListings_ModelId",
                table: "HandpieceStoreListings",
                column: "ModelId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreListings_SerialNumber",
                table: "HandpieceStoreListings",
                column: "SerialNumber");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HandpieceStoreListings");
        }
    }
}
