// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHandpieceStoreListingImages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "MainImageId",
                table: "HandpieceStoreListings",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "HandpieceStoreListingImages",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    ListingId = table.Column<Guid>(nullable: false),
                    OrderNo = table.Column<int>(nullable: false),
                    ImageId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceStoreListingImages", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HandpieceStoreListingImages_UploadedImages_ImageId",
                        column: x => x.ImageId,
                        principalTable: "UploadedImages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_HandpieceStoreListingImages_HandpieceStoreListings_ListingId",
                        column: x => x.ListingId,
                        principalTable: "HandpieceStoreListings",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreListings_MainImageId",
                table: "HandpieceStoreListings",
                column: "MainImageId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreListingImages_ImageId",
                table: "HandpieceStoreListingImages",
                column: "ImageId");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreListingImages_ListingId_OrderNo",
                table: "HandpieceStoreListingImages",
                columns: new[] { "ListingId", "OrderNo" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_HandpieceStoreListings_UploadedImages_MainImageId",
                table: "HandpieceStoreListings",
                column: "MainImageId",
                principalTable: "UploadedImages",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_HandpieceStoreListings_UploadedImages_MainImageId",
                table: "HandpieceStoreListings");

            migrationBuilder.DropTable(
                name: "HandpieceStoreListingImages");

            migrationBuilder.DropIndex(
                name: "IX_HandpieceStoreListings_MainImageId",
                table: "HandpieceStoreListings");

            migrationBuilder.DropColumn(
                name: "MainImageId",
                table: "HandpieceStoreListings");
        }
    }
}
