// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddFeedbackFormQuestions : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FeedbackFormQuestions",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    OrderNo = table.Column<int>(nullable: false),
                    Type = table.Column<int>(nullable: false),
                    IsEnabled = table.Column<bool>(nullable: false),
                    IsDisplayed = table.Column<bool>(nullable: false),
                    ShortName = table.Column<string>(maxLength: 200, nullable: false),
                    Name = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FeedbackFormQuestions", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_FeedbackFormQuestions_OrderNo",
                table: "FeedbackFormQuestions",
                column: "OrderNo",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FeedbackFormQuestions");
        }
    }
}
