// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddOrderNumberToHandpieceStoreOrders : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "OrderNumber",
                table: "HandpieceStoreOrders",
                nullable: true,
                defaultValue: 0);

            migrationBuilder.Sql(
                @"with [Orders_CTE] ([Id], [OrderNumber], [RowNumber]) as
	              (
	                  select [Id], [OrderNumber], row_number() over (order by [CreatedOn] asc) as [RowNumber]
	                  from [HandpieceStoreOrders]
	              ) update [Orders_CTE] set [OrderNumber] = [RowNumber]",
                suppressTransaction: true);

            migrationBuilder.Sql(
                @"declare @nextId bigint
                  select @nextId = max([OrderNumber]) from [HandpieceStoreOrders]
                  if @nextId is null begin
	                  set @nextId = 0
                  end
                  insert into [EntitySequences] ([Id], [NextSequenceId]) values ('HandpieceStoreOrderNumber', @nextId + 1)",
                suppressTransaction: true);

            migrationBuilder.AlterColumn<int>(
                name: "OrderNumber",
                table: "HandpieceStoreOrders",
                nullable: false,
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceStoreOrders_OrderNumber",
                table: "HandpieceStoreOrders",
                column: "OrderNumber",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_HandpieceStoreOrders_OrderNumber",
                table: "HandpieceStoreOrders");

            migrationBuilder.DropColumn(
                name: "OrderNumber",
                table: "HandpieceStoreOrders");
        }
    }
}
