// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddCorporatePricingServiceLevels : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CorporatePricingServiceLevels",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    ServiceLevelId = table.Column<Guid>(nullable: false),
                    CategoryId = table.Column<Guid>(nullable: false),
                    CostOfRepair = table.Column<decimal>(type: "decimal(18,2)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CorporatePricingServiceLevels", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CorporatePricingServiceLevels_CorporatePricingCategories_CategoryId",
                        column: x => x.CategoryId,
                        principalTable: "CorporatePricingCategories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CorporatePricingServiceLevels_ServiceLevels_ServiceLevelId",
                        column: x => x.ServiceLevelId,
                        principalTable: "ServiceLevels",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CorporatePricingServiceLevels_CategoryId",
                table: "CorporatePricingServiceLevels",
                column: "CategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_CorporatePricingServiceLevels_ServiceLevelId_CategoryId",
                table: "CorporatePricingServiceLevels",
                columns: new[] { "ServiceLevelId", "CategoryId" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CorporatePricingServiceLevels");
        }
    }
}
