// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddFeedbackForms : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FeedbackForms",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    ClientId = table.Column<Guid>(nullable: false),
                    Status = table.Column<int>(nullable: false),
                    SentOn = table.Column<DateTime>(nullable: false),
                    ExpiresOn = table.Column<DateTime>(nullable: true),
                    OpenedOn = table.Column<DateTime>(nullable: true),
                    CompletedOn = table.Column<DateTime>(nullable: true),
                    TotalRating = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FeedbackForms", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FeedbackForms_Clients_ClientId",
                        column: x => x.ClientId,
                        principalTable: "Clients",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "FeedbackFormAnswers",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    FormId = table.Column<Guid>(nullable: false),
                    QuestionId = table.Column<Guid>(nullable: false),
                    IntegerAnswer = table.Column<long>(nullable: true),
                    StringAnswer = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FeedbackFormAnswers", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FeedbackFormAnswers_FeedbackForms_FormId",
                        column: x => x.FormId,
                        principalTable: "FeedbackForms",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_FeedbackFormAnswers_FeedbackFormQuestions_QuestionId",
                        column: x => x.QuestionId,
                        principalTable: "FeedbackFormQuestions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_FeedbackFormAnswers_QuestionId",
                table: "FeedbackFormAnswers",
                column: "QuestionId");

            migrationBuilder.CreateIndex(
                name: "IX_FeedbackFormAnswers_FormId_QuestionId",
                table: "FeedbackFormAnswers",
                columns: new[] { "FormId", "QuestionId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_FeedbackForms_ClientId",
                table: "FeedbackForms",
                column: "ClientId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FeedbackFormAnswers");

            migrationBuilder.DropTable(
                name: "FeedbackForms");
        }
    }
}
