// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddCorporatePricingCategories : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CorporatePricingCategories",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    OrderNo = table.Column<int>(nullable: false),
                    Name = table.Column<string>(maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CorporatePricingCategories", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CorporatePricingCategories_OrderNo",
                table: "CorporatePricingCategories",
                column: "OrderNo",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CorporatePricingCategories");
        }
    }
}
