// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddPricingCategoryToClients : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "PricingCategoryId",
                table: "Clients",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Clients_PricingCategoryId",
                table: "Clients",
                column: "PricingCategoryId");

            migrationBuilder.AddForeignKey(
                name: "FK_Clients_CorporatePricingCategories_PricingCategoryId",
                table: "Clients",
                column: "PricingCategoryId",
                principalTable: "CorporatePricingCategories",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Clients_CorporatePricingCategories_PricingCategoryId",
                table: "Clients");

            migrationBuilder.DropIndex(
                name: "IX_Clients_PricingCategoryId",
                table: "Clients");

            migrationBuilder.DropColumn(
                name: "PricingCategoryId",
                table: "Clients");
        }
    }
}
