// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddInventorySKUs : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "InventorySKUs",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    TypeId = table.Column<Guid>(nullable: false),
                    ParentId = table.Column<Guid>(nullable: true),
                    DefaultChildId = table.Column<Guid>(nullable: true),
                    Name = table.Column<string>(maxLength: 200, nullable: false),
                    NormalizedName = table.Column<string>(maxLength: 200, nullable: false),
                    AveragePrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    WarningQuantity = table.Column<decimal>(type: "decimal(18,3)", nullable: true),
                    Description = table.Column<string>(nullable: true),
                    NodeType = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_InventorySKUs", x => x.Id);
                    table.ForeignKey(
                        name: "FK_InventorySKUs_InventorySKUs_DefaultChildId",
                        column: x => x.DefaultChildId,
                        principalTable: "InventorySKUs",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_InventorySKUs_InventorySKUs_ParentId",
                        column: x => x.ParentId,
                        principalTable: "InventorySKUs",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_InventorySKUs_InventorySKUTypes_TypeId",
                        column: x => x.TypeId,
                        principalTable: "InventorySKUTypes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_InventorySKUs_DefaultChildId",
                table: "InventorySKUs",
                column: "DefaultChildId");

            migrationBuilder.CreateIndex(
                name: "IX_InventorySKUs_ParentId",
                table: "InventorySKUs",
                column: "ParentId");

            migrationBuilder.CreateIndex(
                name: "IX_InventorySKUs_TypeId",
                table: "InventorySKUs",
                column: "TypeId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "InventorySKUs");
        }
    }
}
