// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddShortNameToJobTypes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<String>(
                name: "ShortName",
                table: "JobTypes",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.Sql("update [JobTypes] set [ShortName] = N'Est.' where [Id] = N'Estimate'");
            migrationBuilder.Sql("update [JobTypes] set [ShortName] = N'Sale' where [Id] = N'Sale'");

            migrationBuilder.AlterColumn<String>(
                name: "ShortName",
                table: "JobTypes",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ShortName",
                table: "JobTypes");
        }
    }
}
