// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AlterInventorySKUsQuantityToIncludeRepairQuantity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [dbo].[InventorySKUsQuantity] ([Id], [TotalQuantity], [ShelfQuantity], [TrayQuantity], [OrderedQuantity], [RequestedQuantity], [RepairQuantity])
as
select 
  ascendants.[AscendantId] as [Id],
  sum(case when [Status] in (100) then [Quantity] else 0 end) as [TotalQuantity],
  sum(case when [Status] in (90, 100) then [Quantity] else 0 end) as [ShelfQuantity],
  sum(case when [Status] in (90) then [QuantityAbsolute] else 0 end) as [TrayQuantity],
  sum(case when [Status] in (30) then [Quantity] else 0 end) as [OrderedQuantity],
  sum(case when [Status] in (10, 20) then [Quantity] else 0 end) as [RequestedQuantity],
  sum(case when [Type] in (1000) and [Status] in (40,90) then [QuantityAbsolute] else 0 end) as [RepairQuantity]
from [InventoryMovements] movs
inner join [InventorySKUs] sku on movs.[SKUId] = sku.[Id]
inner join [InventorySKUsAscendants] ascendants on movs.[SKUId] = ascendants.[DescendantId]
where sku.[DeletionStatus] = 0
group by ascendants.[AscendantId]", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [dbo].[InventorySKUsQuantity] ([Id], [TotalQuantity], [ShelfQuantity], [TrayQuantity], [OrderedQuantity], [RequestedQuantity])
as
select 
  ascendants.[AscendantId] as [Id],
  sum(case when [Status] in (100) then [Quantity] else 0 end) as [TotalQuantity],
  sum(case when [Status] in (90, 100) then [Quantity] else 0 end) as [ShelfQuantity],
  sum(case when [Status] in (90) then [QuantityAbsolute] else 0 end) as [TrayQuantity],
  sum(case when [Status] in (30) then [Quantity] else 0 end) as [OrderedQuantity],
  sum(case when [Status] in (10, 20) then [Quantity] else 0 end) as [RequestedQuantity]
from [InventoryMovements] movs
inner join [InventorySKUs] sku on movs.[SKUId] = sku.[Id]
inner join [InventorySKUsAscendants] ascendants on movs.[SKUId] = ascendants.[DescendantId]
where sku.[DeletionStatus] = 0
group by ascendants.[AscendantId]", suppressTransaction: true);
        }
    }
}
