// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddInventorySKUsDescendantsWarningsView : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventorySKUsDescendantsWarnings] ([Id], [HasDescendantsWithWarning])
as
select 
  a.[AscendantId] as [Id],
  max(w.[HasWarning]) as [HasDescendantsWithWarning]
from [InventorySKUsWarnings] w
inner join [InventorySKUsAscendants] a on w.[Id] = a.[DescendantId]
group by a.[AscendantId]", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"drop view [InventorySKUsDescendantsWarnings]", suppressTransaction: true);
        }
    }
}
