// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddVideosToHandpieceImages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_HandpieceImages_UploadedImages_ImageId",
                table: "HandpieceImages");

            migrationBuilder.AlterColumn<Guid>(
                name: "ImageId",
                table: "HandpieceImages",
                type: "uniqueidentifier",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AddColumn<Guid>(
                name: "VideoId",
                table: "HandpieceImages",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceImages_VideoId",
                table: "HandpieceImages",
                column: "VideoId");

            migrationBuilder.AddForeignKey(
                name: "FK_HandpieceImages_UploadedFiles_VideoId",
                table: "HandpieceImages",
                column: "VideoId",
                principalTable: "UploadedFiles",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_HandpieceImages_UploadedImages_ImageId",
                table: "HandpieceImages",
                column: "ImageId",
                principalTable: "UploadedImages",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_HandpieceImages_UploadedFiles_VideoId",
                table: "HandpieceImages");

            migrationBuilder.DropForeignKey(
                name: "FK_HandpieceImages_UploadedImages_ImageId",
                table: "HandpieceImages");

            migrationBuilder.DropIndex(
                name: "IX_HandpieceImages_VideoId",
                table: "HandpieceImages");

            migrationBuilder.DropColumn(
                name: "VideoId",
                table: "HandpieceImages");

            migrationBuilder.Sql("delete from [HandpieceImages] where [ImageId] is null");

            migrationBuilder.AlterColumn<Guid>(
                name: "ImageId",
                table: "HandpieceImages",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_HandpieceImages_UploadedImages_ImageId",
                table: "HandpieceImages",
                column: "ImageId",
                principalTable: "UploadedImages",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
