// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddInventorySKUsMissingQuantityView : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventorySKUsMissingQuantity] ([Id], [MissingQuantity])
as
select
  sku.[Id],
  coalesce(rq.[RequiredQuantity], 0) - (coalesce(q.[ShelfQuantity], 0) + coalesce(q.[OrderedQuantity], 0) + coalesce(q.[RequestedQuantity], 0)) as [MissingQuantity]
from [InventorySKUs] sku
left join [InventorySKUsQuantity] q on q.[Id] = sku.[Id]
left join [InventorySKUsRequiredQuantity] rq on rq.[Id] = sku.[Id]
where sku.[NodeType] = 0 and sku.[DeletionStatus] = 0
  and (coalesce(rq.[RequiredQuantity], 0) - (coalesce(q.[ShelfQuantity], 0) + coalesce(q.[OrderedQuantity], 0) + coalesce(q.[RequestedQuantity], 0))) > 0", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"drop view [InventorySKUsMissingQuantity]", suppressTransaction: true);
        }
    }
}
