// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddApprovedOnAndByToHandpieces : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "ApprovedById",
                table: "Handpieces",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ApprovedOn",
                table: "Handpieces",
                type: "datetime2",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Handpieces_ApprovedById",
                table: "Handpieces",
                column: "ApprovedById");

            migrationBuilder.AddForeignKey(
                name: "FK_Handpieces_Employees_ApprovedById",
                table: "Handpieces",
                column: "ApprovedById",
                principalTable: "Employees",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Handpieces_Employees_ApprovedById",
                table: "Handpieces");

            migrationBuilder.DropIndex(
                name: "IX_Handpieces_ApprovedById",
                table: "Handpieces");

            migrationBuilder.DropColumn(
                name: "ApprovedById",
                table: "Handpieces");

            migrationBuilder.DropColumn(
                name: "ApprovedOn",
                table: "Handpieces");
        }
    }
}
