// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddOrderNoToInventorySKUs : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_InventorySKUTypes_OrderNo",
                table: "InventorySKUTypes");

            migrationBuilder.DropIndex(
                name: "IX_InventorySKUs_TypeId",
                table: "InventorySKUs");

            migrationBuilder.AddColumn<int>(
                name: "OrderNo",
                table: "InventorySKUs",
                type: "int",
                nullable: true);

            migrationBuilder.Sql(@";
with [OrderedSKUs] as (
	select 
	  [Id],
	  [TypeId],
	  [ParentId],
	  [OrderNo],
	  row_number() over (partition by [TypeId], [ParentId] order by [Name] asc) as [NewOrderNo]
	from [InventorySKUs]
)
update [OrderedSKUs] set [OrderNo] = [NewOrderNo]", suppressTransaction: true);

            migrationBuilder.AlterColumn<int>(
                name: "OrderNo",
                table: "InventorySKUs",
                type: "int",
                nullable: false);

            migrationBuilder.CreateIndex(
                name: "IX_InventorySKUTypes_OrderNo",
                table: "InventorySKUTypes",
                column: "OrderNo",
                unique: true,
                filter: "[DeletionStatus] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_InventorySKUs_TypeId_OrderNo",
                table: "InventorySKUs",
                columns: new[] { "TypeId", "OrderNo" },
                unique: true,
                filter: "[ParentId] is null and [DeletionStatus] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_InventorySKUs_TypeId_ParentId_OrderNo",
                table: "InventorySKUs",
                columns: new[] { "TypeId", "ParentId", "OrderNo" },
                unique: true,
                filter: "[ParentId] is not null and [DeletionStatus] = 0");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_InventorySKUTypes_OrderNo",
                table: "InventorySKUTypes");

            migrationBuilder.DropIndex(
                name: "IX_InventorySKUs_TypeId_OrderNo",
                table: "InventorySKUs");

            migrationBuilder.DropIndex(
                name: "IX_InventorySKUs_TypeId_ParentId_OrderNo",
                table: "InventorySKUs");

            migrationBuilder.DropColumn(
                name: "OrderNo",
                table: "InventorySKUs");

            migrationBuilder.CreateIndex(
                name: "IX_InventorySKUTypes_OrderNo",
                table: "InventorySKUTypes",
                column: "OrderNo",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_InventorySKUs_TypeId",
                table: "InventorySKUs",
                column: "TypeId");
        }
    }
}
