// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class UpgradeStatisticsModeInInventorySKUTypes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "StatisticsMode",
                table: "InventorySKUTypes",
                type: "int",
                nullable: true);

            migrationBuilder.Sql(@"update [InventorySKUTypes] set [StatisticsMode] = case [ShowInStatistics] when 1 then 1 when 0 then 0 end", suppressTransaction: true);

            migrationBuilder.AlterColumn<int>(
                name: "StatisticsMode",
                table: "InventorySKUTypes",
                type: "int",
                nullable: false);

            migrationBuilder.DropColumn(
                name: "ShowInStatistics",
                table: "InventorySKUTypes");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "ShowInStatistics",
                table: "InventorySKUTypes",
                type: "bit",
                nullable: true);

            migrationBuilder.Sql(@"update [InventorySKUTypes] set [ShowInStatistics] = case [StatisticsMode] when 0 then 0 else 1 end", suppressTransaction: true);

            migrationBuilder.AlterColumn<bool>(
                name: "ShowInStatistics",
                table: "InventorySKUTypes",
                type: "bit",
                nullable: false);

            migrationBuilder.DropColumn(
                name: "StatisticsMode",
                table: "InventorySKUTypes");
        }
    }
}
