// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddClientNotificationsOptions : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "NotificationsOptions",
                table: "Clients",
                type: "int",
                nullable: true);

            migrationBuilder.Sql("update [Clients] set [NotificationsOptions] = case [EmailsEnabled] when 1 then 1 else 0 end");

            migrationBuilder.DropColumn(
                name: "EmailsEnabled",
                table: "Clients");

            migrationBuilder.AlterColumn<int>(
                name: "NotificationsOptions",
                table: "Clients",
                type: "int",
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "NotificationsOptions",
                table: "Clients");

            migrationBuilder.AddColumn<bool>(
                name: "EmailsEnabled",
                table: "Clients",
                type: "bit",
                nullable: true);

            migrationBuilder.Sql("update [Clients] set [EmailsEnabled] = 0");

            migrationBuilder.AlterColumn<bool>(
                name: "EmailsEnabled",
                table: "Clients",
                type: "bit",
                nullable: false);
        }
    }
}
