// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddTotalRemindersCountToClientRepairItemOverrides : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "TotalRemindersCount",
                table: "ClientRepairedItemOverrides",
                type: "int",
                nullable: true);

            migrationBuilder.Sql(@"update [ClientRepairedItemOverrides] set [TotalRemindersCount] = [RemindersCount]");

            migrationBuilder.AlterColumn<int>(
                name: "TotalRemindersCount",
                table: "ClientRepairedItemOverrides",
                type: "int",
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "TotalRemindersCount",
                table: "ClientRepairedItemOverrides");
        }
    }
}
