// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddDisableRemindersToServiceLevels : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "DisableReminders",
                table: "ServiceLevels",
                type: "bit",
                nullable: true);

            migrationBuilder.Sql("update [ServiceLevels] set [DisableReminders] = 0");

            migrationBuilder.AlterColumn<bool>(
                name: "DisableReminders",
                table: "ServiceLevels",
                type: "bit",
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DisableReminders",
                table: "ServiceLevels");
        }
    }
}
