// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddInventorySKUsRequiredQuantityView : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventorySKUsRequiredQuantity] ([Id], [RequiredQuantity])
as
with [GroupFinalChild] ([Id], [ChildParent], [DefaultChildId])
as
(
    select sku.[Id], sku.[Id], sku.[DefaultChildId]
	from [InventorySKUs] sku
	where sku.[NodeType] = 1 and sku.[DeletionStatus] = 0 and sku.[DefaultChildId] is not null
	union all
	select q.[Id], sku.[Id], sku.[DefaultChildId]
	from [GroupFinalChild] q
	inner join [InventorySKUs] sku on q.[DefaultChildId] = sku.[Id] and q.[ChildParent] = sku.[ParentId] and sku.[DeletionStatus] = 0 and sku.[DefaultChildId] is not null
), [SKUFinalChild] ([SourceId], [FinalId])
as
(
    select [Id] as [SourceId], [Id] as [FinalId] from [InventorySKUs] sku
    where sku.[NodeType] = 0 and sku.[DeletionStatus] = 0
    union all
    select fc.[DefaultChildId], fc.[Id] from [GroupFinalChild] fc inner join [InventorySKUs] sku on fc.[DefaultChildId] = sku.[Id] and sku.[NodeType] = 0 and sku.[DeletionStatus] = 0
)
select fc.[SourceId] as [Id], max(coalesce(sku.[WarningQuantity], 0)) as [RequiredQuantity]
from [SKUFinalChild] fc
inner join [InventorySKUs] sku on fc.[FinalId] = sku.[Id]
group by fc.[SourceId]", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"drop view [InventorySKUsRequiredQuantity]", suppressTransaction: true);
        }
    }
}
