// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class MakeMovementIdUniqueInHandpieceRequiredPartMovements : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_HandpieceRequiredPartMovements_MovementId",
                table: "HandpieceRequiredPartMovements");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceRequiredPartMovements_MovementId",
                table: "HandpieceRequiredPartMovements",
                column: "MovementId",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_HandpieceRequiredPartMovements_MovementId",
                table: "HandpieceRequiredPartMovements");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceRequiredPartMovements_MovementId",
                table: "HandpieceRequiredPartMovements",
                column: "MovementId");
        }
    }
}
