// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddShowInStatisticsToInventorySKUTypes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "ShowInStatistics",
                table: "InventorySKUTypes",
                type: "bit",
                nullable: true);

            migrationBuilder.Sql(@"update [InventorySKUTypes] set [ShowInStatistics] = 0", suppressTransaction: true);

            migrationBuilder.AlterColumn<bool>(
                name: "ShowInStatistics",
                table: "InventorySKUTypes",
                type: "bit",
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ShowInStatistics",
                table: "InventorySKUTypes");
        }
    }
}
