// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class UpdateInventorySKUsHierarchyViewToIncludeHierarchyOrderNo : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventorySKUsHierarchy] ([Id], [ParentId], [HierarchyId], [Level], [HierarchyOrderNo])
as
with [Hierarchy] ([Id], [ParentId], [HierarchyId], [Level], [UnpaddedOrder])
as
(
	select s1.[Id], s1.[ParentId], cast(cast(s1.[Id] as binary(16)) as varbinary(320)) as [HierarchyId], 0 as [Level], cast(cast(s1.[OrderNo] as binary(4)) as varbinary(80)) as [UnpaddedOrder]
	from [InventorySKUs] s1
	where s1.[ParentId] is null
	union all
	select s1.[Id], s1.[ParentId], cast(s2.[HierarchyId] + cast(s1.[Id] as varbinary(16)) as varbinary(320)) as [HierarchyId], s2.[Level] + 1 as [Level], cast((s2.[UnpaddedOrder] + cast(s1.[OrderNo] as binary(4))) as varbinary(80)) as [UnpaddedOrder]
	from [InventorySKUs] s1 inner join [Hierarchy] s2 on s1.[ParentId] = s2.[Id]
)
select [Id], [ParentId], [HierarchyId], [Level], cast([UnpaddedOrder] as binary(80)) as [HierarchyOrderNo] from [Hierarchy]", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventorySKUsHierarchy] ([Id], [ParentId], [HierarchyId], [Level])
as
with [Hierarchy] ([Id], [ParentId], [HierarchyId], [Level])
as
(
	select s1.[Id], s1.[ParentId], cast(cast(s1.[Id] as binary(16)) as varbinary(320)) as [HierarchyId], 0 as [Level]
	from [InventorySKUs] s1
	where s1.[ParentId] is null
	union all
	select s1.[Id], s1.[ParentId], cast(s2.[HierarchyId] + cast(s1.[Id] as varbinary(16)) as varbinary(320)) as [HierarchyId], s2.[Level] + 1 as [Level]
	from [InventorySKUs] s1 inner join [Hierarchy] s2 on s1.[ParentId] = s2.[Id]
)
select [Id], [ParentId], [HierarchyId], [Level] from [Hierarchy]", suppressTransaction: true);
        }
    }
}
