// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddInventorySKUsQuantityView : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventorySKUsQuantity] ([Id], [TotalQuantity], [ShelfQuantity], [TrayQuantity], [OrderedQuantity], [RequestedQuantity])
as
select 
  ascendants.[AscendantId] as [Id],
  sum(case when [Status] in (100) then [Quantity] else 0 end) as [TotalQuantity],
  sum(case when [Status] in (90, 100) then [Quantity] else 0 end) as [ShelfQuantity],
  sum(case when [Status] in (90) then [QuantityAbsolute] else 0 end) as [TrayQuantity],
  sum(case when [Status] in (30) then [Quantity] else 0 end) as [OrderedQuantity],
  sum(case when [Status] in (10, 20) then [Quantity] else 0 end) as [RequestedQuantity]
from [InventoryMovements] movs
inner join [InventorySKUsAscendants] ascendants on movs.[SKUId] = ascendants.[DescendantId]
group by ascendants.[AscendantId]", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"drop view [InventorySKUsQuantity]", suppressTransaction: true);
        }
    }
}
