// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class ExtendedHandpiecePartsOutOfStockToEnum : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "PartsOutOfStock",
                table: "Handpieces",
                type: "int",
                nullable: false,
                oldClrType: typeof(bool),
                oldType: "bit");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"update [Handpieces] set [PartsOutOfStock] where [PartsOutOfStock] > 1", suppressTransaction: true);
            migrationBuilder.AlterColumn<bool>(
                name: "PartsOutOfStock",
                table: "Handpieces",
                type: "bit",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int");
        }
    }
}
