// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class MakeHandpieceRequiredPartSKUUnique : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Removing all handpiece required parts and repair movements.
            migrationBuilder.Sql(@"delete from [HandpieceRequiredParts]", suppressTransaction: true);
            migrationBuilder.Sql(@"delete from [InventoryMovements] where [Type] = 1000", suppressTransaction: true);

            migrationBuilder.DropIndex(
                name: "IX_HandpieceRequiredParts_HandpieceId",
                table: "HandpieceRequiredParts");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceRequiredParts_HandpieceId_SKUId",
                table: "HandpieceRequiredParts",
                columns: new[] { "HandpieceId", "SKUId" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_HandpieceRequiredParts_HandpieceId_SKUId",
                table: "HandpieceRequiredParts");

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceRequiredParts_HandpieceId",
                table: "HandpieceRequiredParts",
                column: "HandpieceId");
        }
    }
}
