// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class UpdateInventorySKUsViewsToSupportDeletionStatus : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventorySKUsQuantity] ([Id], [TotalQuantity], [ShelfQuantity], [TrayQuantity], [OrderedQuantity], [RequestedQuantity])
as
select 
  ascendants.[AscendantId] as [Id],
  sum(case when [Status] in (100) then [Quantity] else 0 end) as [TotalQuantity],
  sum(case when [Status] in (90, 100) then [Quantity] else 0 end) as [ShelfQuantity],
  sum(case when [Status] in (90) then [QuantityAbsolute] else 0 end) as [TrayQuantity],
  sum(case when [Status] in (30) then [Quantity] else 0 end) as [OrderedQuantity],
  sum(case when [Status] in (10, 20) then [Quantity] else 0 end) as [RequestedQuantity]
from [InventoryMovements] movs
inner join [InventorySKUs] sku on movs.[SKUId] = sku.[Id]
inner join [InventorySKUsAscendants] ascendants on movs.[SKUId] = ascendants.[DescendantId]
where sku.[DeletionStatus] = 0
group by ascendants.[AscendantId]", suppressTransaction: true);

            migrationBuilder.Sql(@"create or alter view [InventorySKUsWarnings] ([Id], [HasWarning])
as
select 
  sku.[Id],
  case when sku.[WarningQuantity] is not null and sku.[WarningQuantity] >= coalesce(q.[ShelfQuantity], 0) then 1 else 0 end as [HasWarning]
from [InventorySKUs] sku
left join [InventorySKUsQuantity] q on sku.[Id] = q.[Id]
where sku.[DeletionStatus] = 0", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventorySKUsQuantity] ([Id], [TotalQuantity], [ShelfQuantity], [TrayQuantity], [OrderedQuantity], [RequestedQuantity])
as
select 
  ascendants.[AscendantId] as [Id],
  sum(case when [Status] in (100) then [Quantity] else 0 end) as [TotalQuantity],
  sum(case when [Status] in (90, 100) then [Quantity] else 0 end) as [ShelfQuantity],
  sum(case when [Status] in (90) then [QuantityAbsolute] else 0 end) as [TrayQuantity],
  sum(case when [Status] in (30) then [Quantity] else 0 end) as [OrderedQuantity],
  sum(case when [Status] in (10, 20) then [Quantity] else 0 end) as [RequestedQuantity]
from [InventoryMovements] movs
inner join [InventorySKUsAscendants] ascendants on movs.[SKUId] = ascendants.[DescendantId]
group by ascendants.[AscendantId]", suppressTransaction: true);

            migrationBuilder.Sql(@"create or alter view [InventorySKUsWarnings] ([Id], [HasWarning])
as
select 
  sku.[Id],
  case when sku.[WarningQuantity] is not null and sku.[WarningQuantity] >= coalesce(q.[ShelfQuantity], 0) then 1 else 0 end as [HasWarning]
from [InventorySKUs] sku left join [InventorySKUsQuantity] q on sku.[Id] = q.[Id]", suppressTransaction: true);
        }
    }
}
