// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddInventoryMovementChanges : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "InventoryMovementChanges",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SKUId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    MovementId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ChangedOn = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ChangedById = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Action = table.Column<int>(type: "int", nullable: false),
                    OldStatus = table.Column<int>(type: "int", nullable: true),
                    NewStatus = table.Column<int>(type: "int", nullable: true),
                    OldQuantity = table.Column<decimal>(type: "decimal(18,3)", nullable: true),
                    NewQuantity = table.Column<decimal>(type: "decimal(18,3)", nullable: true),
                    OldPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NewPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OldComment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NewComment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OldContent = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NewContent = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_InventoryMovementChanges", x => x.Id);
                    table.ForeignKey(
                        name: "FK_InventoryMovementChanges_Employees_ChangedById",
                        column: x => x.ChangedById,
                        principalTable: "Employees",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_InventoryMovementChanges_InventorySKUs_SKUId",
                        column: x => x.SKUId,
                        principalTable: "InventorySKUs",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_InventoryMovementChanges_ChangedById",
                table: "InventoryMovementChanges",
                column: "ChangedById");

            migrationBuilder.CreateIndex(
                name: "IX_InventoryMovementChanges_SKUId",
                table: "InventoryMovementChanges",
                column: "SKUId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "InventoryMovementChanges");
        }
    }
}
