// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddJobTypes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "JobTypes",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Name = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_JobTypes", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_JobTypes_Name",
                table: "JobTypes",
                column: "Name",
                unique: true);

            migrationBuilder.Sql("insert into [JobTypes] ([Id], [Name]) values (N'Estimate', N'Estimate')");
            migrationBuilder.Sql("insert into [JobTypes] ([Id], [Name]) values (N'Sale', N'Sale')");

            migrationBuilder.AddColumn<string>(
                name: "JobTypeId",
                table: "Jobs",
                type: "nvarchar(20)",
                nullable: true);

            migrationBuilder.Sql("update [Jobs] set [JobTypeId] = N'Estimate'");

            migrationBuilder.AlterColumn<string>(
                name: "JobTypeId",
                table: "Jobs",
                type: "nvarchar(20)",
                nullable: false);

            migrationBuilder.DropIndex(
                name: "IX_Jobs_JobNumber",
                table: "Jobs");

            migrationBuilder.CreateIndex(
                name: "IX_Jobs_JobTypeId_JobNumber",
                table: "Jobs",
                columns: new[] { "JobTypeId", "JobNumber" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Jobs_JobTypes_JobTypeId",
                table: "Jobs",
                column: "JobTypeId",
                principalTable: "JobTypes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.Sql("update [EntitySequences] set [Id] = N'Jobs:Estimate:JobNumber' where [Id] = N'JobNumberSequenceKey'");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Jobs_JobTypes_JobTypeId",
                table: "Jobs");

            migrationBuilder.DropTable(
                name: "JobTypes");

            migrationBuilder.DropIndex(
                name: "IX_Jobs_JobTypeId_JobNumber",
                table: "Jobs");

            migrationBuilder.DropColumn(
                name: "JobTypeId",
                table: "Jobs");

            migrationBuilder.CreateIndex(
                name: "IX_Jobs_JobNumber",
                table: "Jobs",
                column: "JobNumber",
                unique: true);
        }
    }
}
