// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHideFromStatisticToInventorySKUs : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "HideFromStatistic",
                table: "InventorySKUs",
                type: "bit",
                nullable: true);

            migrationBuilder.Sql(@"update [InventorySKUs] set [HideFromStatistic] = 0", suppressTransaction: true);

            migrationBuilder.AlterColumn<bool>(
                name: "HideFromStatistic",
                table: "InventorySKUs",
                type: "bit",
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "HideFromStatistic",
                table: "InventorySKUs");
        }
    }
}
