// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddTutorialPagesAndVideos : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "TutorialPages",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Title = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TutorialPages", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "TutorialVideos",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    PageId = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    OrderNo = table.Column<int>(type: "int", nullable: false),
                    Title = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    VideoUrl = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    Availability = table.Column<int>(type: "int", nullable: false),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TutorialVideos", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TutorialVideos_TutorialPages_PageId",
                        column: x => x.PageId,
                        principalTable: "TutorialPages",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_TutorialVideos_PageId_OrderNo",
                table: "TutorialVideos",
                columns: new[] { "PageId", "OrderNo" },
                unique: true);

            migrationBuilder.InsertData(
                table: "TutorialPages",
                columns: new String[] { "Id", "Title" },
                values: new Object[,]
                {
                    { "Hub", "Hub tutorials" },
                    { "Surgery", "Surgery tutorials" },
                });

            migrationBuilder.InsertData(
                table: "TutorialVideos",
                columns: new String[] { "Id", "PageId", "OrderNo", "Title", "VideoUrl", "Availability" },
                values: new Object[,]
                {
                    { new Guid("18D352C5-A2AE-4E49-B406-20B25CD1C250"), "Hub", 1, "Surgery Overview", "https://www.youtube.com/embed/kVvlfNseVuU", 5 },
                    { new Guid("9F4D93CD-EBA4-48EC-B018-48A4ED115137"), "Hub", 2, "Surgery Reporting Overview", "https://www.youtube.com/embed/7VYZPoHanFc", 5 },
                    { new Guid("BECC16F5-657D-42CE-8ED3-730338974715"), "Hub", 3, "Surgery Reporting Makes and Models", "https://www.youtube.com/embed/QA0JiRodkmc", 5 },
                    { new Guid("D8FDFE74-2739-4C58-8698-30E804D3DA77"), "Hub", 4, "Surgery Reporting Status", "https://www.youtube.com/embed/k3lYo7ghij0", 5 },

                    { new Guid("71C5E5AA-3629-432C-9867-8700D3F83992"), "Hub", 5, "Corporate Overview", "https://www.youtube.com/embed/Niq6YXWk-Ko", 6 },
                    { new Guid("BCEB0569-31E3-4C71-B928-2B48C9D00D8B"), "Hub", 6, "Corporate Reporting Overview", "https://www.youtube.com/embed/Igb12gfBQ2U", 6 },
                    { new Guid("1316AAE4-8440-46BE-889B-47FC739D73B5"), "Hub", 7, "Corporate Reporting Surgeries", "https://www.youtube.com/embed/Y44ai8JR5mk", 6 },
                    { new Guid("F76851D3-089E-44FB-B323-A0F888BBECC1"), "Hub", 8, "Corporate Reporting Surgeries Aggregate", "https://www.youtube.com/embed/4_Ruz-QY19A", 6 },
                    { new Guid("C8746B96-93D5-4592-82B6-B64FB4B3483B"), "Hub", 9, "Corporate Reporting Makes and Models", "https://www.youtube.com/embed/lVBGhRmflME", 6 },
                    { new Guid("97CF630B-BE01-4389-950C-F8566A695249"), "Hub", 10, "Corporate Reporting Status", "https://www.youtube.com/embed/l9vdwA5HU3w", 6 },

                    { new Guid("88CC3F16-830A-419C-847A-8FE99A60315E"), "Surgery", 1, "10 steps", "https://www.youtube.com/embed/ww4hCPaNMzA", 7 },
                    { new Guid("69E989A5-F46B-4B71-AAB4-5862C8521836"), "Surgery", 2, "Nozzle", "https://www.youtube.com/embed/nxG44QoVtkg", 7 },
                    { new Guid("C4D3F827-B21A-434F-9C24-F4BB88B30804"), "Surgery", 3, "LowSpeed Stuck bur", "https://www.youtube.com/embed/Uq4RH8nQKz8", 7 },
                    { new Guid("51548B0A-4D09-4B2F-B6E5-7934060FCA84"), "Surgery", 4, "HighSpeed stuck bur", "https://www.youtube.com/embed/TPOOHFDoqh8", 7 },
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TutorialVideos");

            migrationBuilder.DropTable(
                name: "TutorialPages");
        }
    }
}
