// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddInventorySKUsAscendantsView : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventorySKUsAscendants] ([DescendantId], [AscendantId])
as
with [Ascendants] ([DescendantId], [AscendantId])
as
(
	select s1.[Id], s1.[Id] from [InventorySKUs] s1
	union all
	select s1.[Id], p.[AscendantId] from [InventorySKUs] s1 inner join [Ascendants] p on s1.[ParentId] = p.[DescendantId]
)
select [DescendantId], [AscendantId] from [Ascendants]", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"drop view [InventorySKUsAscendants]", suppressTransaction: true);
        }
    }
}
