// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddOrderToHandpieceDiagnostic : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Id",
                table: "HandpieceDiagnostics");

            migrationBuilder.AddColumn<int>(
                name: "OrderNo",
                table: "HandpieceDiagnostics",
                type: "int",
                nullable: true);

            migrationBuilder.Sql(@"update
  [HandpieceDiagnostics]
set
  [OrderNo] = q.[OrderNo]
from (select
  hd.[HandpieceId],
  hd.[ItemId],
  row_number() over (partition by hd.[HandpieceId] order by dci.[Name]) as [OrderNo]
from [HandpieceDiagnostics] hd
inner join [DiagnosticCheckItems] dci on dci.[Id] = hd.[ItemId]) q
where q.[HandpieceId] = [HandpieceDiagnostics].[HandpieceId] and q.[ItemId] = [HandpieceDiagnostics].[ItemId]");

            migrationBuilder.AlterColumn<int>(
                name: "OrderNo",
                table: "HandpieceDiagnostics",
                type: "int",
                nullable: false);

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceDiagnostics_HandpieceId_OrderNo",
                table: "HandpieceDiagnostics",
                columns: new[] { "HandpieceId", "OrderNo" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_HandpieceDiagnostics_HandpieceId_OrderNo",
                table: "HandpieceDiagnostics");

            migrationBuilder.DropColumn(
                name: "OrderNo",
                table: "HandpieceDiagnostics");

            migrationBuilder.AddColumn<Guid>(
                name: "Id",
                table: "HandpieceDiagnostics",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.Sql(@"update [HandpieceDiagnostics] set [Id] = '00000000-0000-0000-0000-000000000000'");

            migrationBuilder.AlterColumn<Guid>(
                name: "Id",
                table: "HandpieceDiagnostics",
                type: "uniqueidentifier",
                nullable: false);
        }
    }
}
