// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddClientHandpieces : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ClientHandpieces",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ClientId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Brand = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Model = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Serial = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    ComponentsText = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ClientHandpieces", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ClientHandpieces_Clients_ClientId",
                        column: x => x.ClientId,
                        principalTable: "Clients",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ClientHandpieceComponents",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ClientHandpieceId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    OrderNo = table.Column<int>(type: "int", nullable: false),
                    Brand = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Model = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Serial = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ClientHandpieceComponents", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ClientHandpieceComponents_ClientHandpieces_ClientHandpieceId",
                        column: x => x.ClientHandpieceId,
                        principalTable: "ClientHandpieces",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.AddColumn<Guid>(
                name: "ClientHandpieceId",
                table: "Handpieces",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.Sql(@"
declare @ClientId uniqueidentifier
declare @ClientHandpieceId uniqueidentifier
declare @HandpieceId uniqueidentifier
declare @Brand nvarchar(100)
declare @Model nvarchar(200)
declare @Serial nvarchar(200)
declare @ComponentsText nvarchar(max)

declare HandpieceCursor 
  cursor local static read_only forward_only
  for select j.[ClientId], h.[Id] as [HandpieceId], trim(h.[Brand]), trim(h.[MakeAndModel]), trim(h.[Serial]), trim(coalesce(h.[ComponentsText],'')) from [Handpieces] h inner join [Jobs] j on h.[JobId] = j.[Id] order by 1, 2, 3, 4, 5
open HandpieceCursor

fetch next from HandpieceCursor into @ClientId, @HandpieceId, @Brand, @Model, @Serial, @ComponentsText
while @@fetch_status = 0 begin
	set @ClientHandpieceId = null
	select @ClientHandpieceId = [Id] from [ClientHandpieces] where [ClientId] = @ClientId and [Brand] = @Brand and [Model] = @Model and [Serial] = @Serial and [ComponentsText] = @ComponentsText
	if @ClientHandpieceId is null begin
	    set @ClientHandpieceId = newid()

		insert into [ClientHandpieces] ([Id], [ClientId], [Brand], [Model], [Serial], [ComponentsText])
		    values (@ClientHandpieceId, @ClientId, @Brand, @Model, @Serial, @ComponentsText)

		insert into [ClientHandpieceComponents] ([Id], [ClientHandpieceId], [OrderNo], [Brand], [Model], [Serial])
		    select newid(), @ClientHandpieceId, [OrderNo], [Brand], [Model], [Serial] from [HandpieceComponents] where [HandpieceId] = @HandpieceId
	end

	update [Handpieces] set [ClientHandpieceId] = @ClientHandpieceId where [Id] = @HandpieceId

	fetch next from HandpieceCursor into @ClientId, @HandpieceId, @Brand, @Model, @Serial, @ComponentsText
end
close HandpieceCursor
deallocate HandpieceCursor");

            migrationBuilder.AlterColumn<Guid>(
                name: "ClientHandpieceId",
                table: "Handpieces",
                type: "uniqueidentifier",
                nullable: false);

            migrationBuilder.CreateIndex(
                name: "IX_Handpieces_ClientHandpieceId",
                table: "Handpieces",
                column: "ClientHandpieceId");

            migrationBuilder.CreateIndex(
                name: "IX_ClientHandpieceComponents_ClientHandpieceId",
                table: "ClientHandpieceComponents",
                column: "ClientHandpieceId");

            migrationBuilder.CreateIndex(
                name: "IX_ClientHandpieces_ClientId",
                table: "ClientHandpieces",
                column: "ClientId");

            migrationBuilder.AddForeignKey(
                name: "FK_Handpieces_ClientHandpieces_ClientHandpieceId",
                table: "Handpieces",
                column: "ClientHandpieceId",
                principalTable: "ClientHandpieces",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Handpieces_ClientHandpieces_ClientHandpieceId",
                table: "Handpieces");

            migrationBuilder.DropTable(
                name: "ClientHandpieceComponents");

            migrationBuilder.DropTable(
                name: "ClientHandpieces");

            migrationBuilder.DropIndex(
                name: "IX_Handpieces_ClientHandpieceId",
                table: "Handpieces");

            migrationBuilder.DropColumn(
                name: "ClientHandpieceId",
                table: "Handpieces");
        }
    }
}
