// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddRemindersInfoToClientHandpieces : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "RemindersDisabled",
                table: "ClientHandpieces",
                type: "bit",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "RemindersLastDateTime",
                table: "ClientHandpieces",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "RemindersLastHandpieceId",
                table: "ClientHandpieces",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "RemindersRecentCount",
                table: "ClientHandpieces",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "RemindersTotalCount",
                table: "ClientHandpieces",
                type: "int",
                nullable: true);

            migrationBuilder.Sql("update [ClientHandpieces] set [RemindersDisabled] = 0, [RemindersRecentCount] = 0, [RemindersTotalCount] = 0");

            migrationBuilder.AlterColumn<bool>(
                name: "RemindersDisabled",
                table: "ClientHandpieces",
                type: "bit",
                nullable: false);

            migrationBuilder.AlterColumn<int>(
                name: "RemindersRecentCount",
                table: "ClientHandpieces",
                type: "int",
                nullable: false);

            migrationBuilder.AlterColumn<int>(
                name: "RemindersTotalCount",
                table: "ClientHandpieces",
                type: "int",
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "RemindersDisabled",
                table: "ClientHandpieces");

            migrationBuilder.DropColumn(
                name: "RemindersLastDateTime",
                table: "ClientHandpieces");

            migrationBuilder.DropColumn(
                name: "RemindersLastHandpieceId",
                table: "ClientHandpieces");

            migrationBuilder.DropColumn(
                name: "RemindersRecentCount",
                table: "ClientHandpieces");

            migrationBuilder.DropColumn(
                name: "RemindersTotalCount",
                table: "ClientHandpieces");
        }
    }
}
