// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AlterInventoryMovementsLinkedHandpiecesViewsToIncludePartsComment : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventoryMovementLinkedHandpieces] (
  [Id], [JobId], [JobNumber], [JobStatus], [HandpieceId], [HandpieceNumber], [HandpieceStatus], [HandpiecePartsComment]
) as
select distinct 
  im.[Id],
  j.[Id] as [JobId],
  j.[JobNumber],
  j.[Status] as [JobStatus],
  h.[Id] as [HandpieceId],
  format(j.[JobNumber], 'D') + '-' + format(h.[JobPosition], 'D') as [HandpieceNumber],
  h.[HandpieceStatus] as [HandpieceStatus],
  h.[PartsComment] as [HandpiecePartsComment]
from [InventoryMovements] im
left join [HandpieceRequiredPartMovements] hrpm on hrpm.[MovementId] = im.[Id]
left join [HandpieceRequiredParts] hrp on hrp.[Id] = hrpm.[RequiredPartId]
left join [Handpieces] h on h.[Id] = hrp.[HandpieceId]
left join [Jobs] j on j.[Id] = h.[JobId]", suppressTransaction: true);

            migrationBuilder.Sql(@"create or alter view [InventoryMovementLinkedAggregatedHandpieces] (
  [Id], [JobsCount], [JobsIds], [JobsNumbers], [JobsStatuses], [HandpiecesCount], [HandpiecesIds], [HandpiecesNumbers], [HandpiecesStatuses], [HandpiecesPartsComments]
) as
select
  im.[Id],
  count(distinct lh.[JobId]) as [JobsCount],
  string_agg(cast(lh.[JobId] as nvarchar(36)), ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [JobsIds],
  string_agg(lh.[JobNumber], ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [JobsNumbers],
  string_agg(lh.[JobStatus], ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [JobsStatuses],
  count(distinct lh.[HandpieceId]) as [HandpiecesCount],
  string_agg(cast(lh.[HandpieceId] as nvarchar(36)), ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [HandpiecesIds],
  string_agg(lh.[HandpieceNumber], ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [HandpiecesNumbers],
  string_agg(lh.[HandpieceStatus], ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [HandpiecesStatuses],
  string_agg(lh.[HandpiecePartsComment], ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [HandpiecesPartsComments]
from [InventoryMovements] im
left join [InventoryMovementLinkedHandpieces] lh on lh.[Id] = im.[Id]
group by im.[Id]", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventoryMovementLinkedHandpieces] (
  [Id], [JobId], [JobNumber], [JobStatus], [HandpieceId], [HandpieceNumber], [HandpieceStatus]
) as
select distinct 
  im.[Id],
  j.[Id] as [JobId],
  j.[JobNumber],
  j.[Status] as [JobStatus],
  h.[Id] as [HandpieceId],
  format(j.[JobNumber], 'D') + '-' + format(h.[JobPosition], 'D') as [HandpieceNumber],
  h.[HandpieceStatus] as [HandpieceStatus]
from [InventoryMovements] im
left join [HandpieceRequiredPartMovements] hrpm on hrpm.[MovementId] = im.[Id]
left join [HandpieceRequiredParts] hrp on hrp.[Id] = hrpm.[RequiredPartId]
left join [Handpieces] h on h.[Id] = hrp.[HandpieceId]
left join [Jobs] j on j.[Id] = h.[JobId]", suppressTransaction: true);

            migrationBuilder.Sql(@"create or alter view [InventoryMovementLinkedAggregatedHandpieces] (
  [Id], [JobsCount], [JobsIds], [JobsNumbers], [JobsStatuses], [HandpiecesCount], [HandpiecesIds], [HandpiecesNumbers], [HandpiecesStatuses]
) as
select
  im.[Id],
  count(distinct lh.[JobId]) as [JobsCount],
  string_agg(cast(lh.[JobId] as nvarchar(36)), ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [JobsIds],
  string_agg(lh.[JobNumber], ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [JobsNumbers],
  string_agg(lh.[JobStatus], ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [JobsStatuses],
  count(distinct lh.[HandpieceId]) as [HandpiecesCount],
  string_agg(cast(lh.[HandpieceId] as nvarchar(36)), ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [HandpiecesIds],
  string_agg(lh.[HandpieceNumber], ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [HandpiecesNumbers],
  string_agg(lh.[HandpieceStatus], ';') within group (order by lh.[JobId], lh.[HandpieceId]) as [HandpiecesStatuses]
from [InventoryMovements] im
left join [InventoryMovementLinkedHandpieces] lh on lh.[Id] = im.[Id]
group by im.[Id]", suppressTransaction: true);
        }
    }
}
