// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddHandpieceRequiredPartMovements : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HandpieceRequiredPartMovements",
                columns: table => new
                {
                    RequiredPartId = table.Column<Guid>(nullable: false),
                    MovementId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HandpieceRequiredPartMovements", x => new { x.RequiredPartId, x.MovementId });
                    table.ForeignKey(
                        name: "FK_HandpieceRequiredPartMovements_InventoryMovements_MovementId",
                        column: x => x.MovementId,
                        principalTable: "InventoryMovements",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_HandpieceRequiredPartMovements_HandpieceRequiredParts_RequiredPartId",
                        column: x => x.RequiredPartId,
                        principalTable: "HandpieceRequiredParts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HandpieceRequiredPartMovements_MovementId",
                table: "HandpieceRequiredPartMovements",
                column: "MovementId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HandpieceRequiredPartMovements");
        }
    }
}
