// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddRemindersInfoToRepairedItemOverride : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "RemindersCount",
                table: "ClientRepairedItemOverrides",
                type: "int",
                nullable: true);

            migrationBuilder.Sql(@"update [ClientRepairedItemOverrides] set [RemindersCount] = 0");

            migrationBuilder.AlterColumn<int>(
                name: "RemindersCount",
                table: "ClientRepairedItemOverrides",
                type: "int",
                nullable: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "RemindersLastDateTime",
                table: "ClientRepairedItemOverrides",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "RemindersLastHandpieceId",
                table: "ClientRepairedItemOverrides",
                type: "uniqueidentifier",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "RemindersCount",
                table: "ClientRepairedItemOverrides");

            migrationBuilder.DropColumn(
                name: "RemindersLastDateTime",
                table: "ClientRepairedItemOverrides");

            migrationBuilder.DropColumn(
                name: "RemindersLastHandpieceId",
                table: "ClientRepairedItemOverrides");
        }
    }
}
