// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddDeletionStatusToInventorySKUsAndTypes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "DeletionStatus",
                table: "InventorySKUTypes",
                type: "int",
                nullable: true);

            migrationBuilder.Sql(@"update [InventorySKUTypes] set [DeletionStatus] = 0", suppressTransaction: true);

            migrationBuilder.AlterColumn<int>(
                name: "DeletionStatus",
                table: "InventorySKUTypes",
                type: "int",
                nullable: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletionDate",
                table: "InventorySKUTypes",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DeletionStatus",
                table: "InventorySKUs",
                type: "int",
                nullable: true);

            migrationBuilder.Sql(@"update [InventorySKUs] set [DeletionStatus] = 0", suppressTransaction: true);

            migrationBuilder.AlterColumn<int>(
                name: "DeletionStatus",
                table: "InventorySKUs",
                type: "int",
                nullable: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletionDate",
                table: "InventorySKUs",
                type: "datetime2",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DeletionDate",
                table: "InventorySKUTypes");

            migrationBuilder.DropColumn(
                name: "DeletionStatus",
                table: "InventorySKUTypes");

            migrationBuilder.DropColumn(
                name: "DeletionDate",
                table: "InventorySKUs");

            migrationBuilder.DropColumn(
                name: "DeletionStatus",
                table: "InventorySKUs");
        }
    }
}
