// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace DentalDrill.CRM.Data.Migrations
{
    public partial class AddInventoryMovementLinkedHandpiecesView : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"create or alter view [InventoryMovementLinkedHandpieces] (
  [Id], [JobId], [JobNumber], [JobStatus], [HandpieceId], [HandpieceNumber], [HandpieceStatus]
) as
select distinct 
  im.[Id],
  j.[Id] as [JobId],
  j.[JobNumber],
  j.[Status] as [JobStatus],
  h.[Id] as [HandpieceId],
  format(j.[JobNumber], 'D') + '-' + format(h.[JobPosition], 'D') as [HandpieceNumber],
  h.[HandpieceStatus] as [HandpieceStatus]
from [InventoryMovements] im
left join [HandpieceRequiredPartMovements] hrpm on hrpm.[MovementId] = im.[Id]
left join [HandpieceRequiredParts] hrp on hrp.[Id] = hrpm.[RequiredPartId]
left join [Handpieces] h on h.[Id] = hrp.[HandpieceId]
left join [Jobs] j on j.[Id] = h.[JobId]", suppressTransaction: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"drop view [InventoryMovementLinkedHandpieces]", suppressTransaction: true);
        }
    }
}
