//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDrill.SmartFreight.Client
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.smartfreight.com/online", ConfigurationName="DentalDrill.SmartFreight.Client.SFOv1")]
    internal interface SFOv1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartfreight.com/online/SFOv1/Import", ReplyAction="http://www.smartfreight.com/online/SFOv1/ImportResponse")]
        System.Threading.Tasks.Task<string> ImportAsync(string id, string passwd, string reference, string consignmentxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartfreight.com/online/SFOv1/CostComparison", ReplyAction="http://www.smartfreight.com/online/SFOv1/CostComparisonResponse")]
        System.Threading.Tasks.Task<string> CostComparisonAsync(string id, string passwd, string reference, string consignmentxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartfreight.com/online/SFOv1/CalculateRate", ReplyAction="http://www.smartfreight.com/online/SFOv1/CalculateRateResponse")]
        System.Threading.Tasks.Task<string> CalculateRateAsync(string id, string passwd, string reference, string consignmentxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartfreight.com/online/SFOv1/SOAPRequest", ReplyAction="http://www.smartfreight.com/online/SFOv1/SOAPRequestResponse")]
        System.Threading.Tasks.Task<string> SOAPRequestAsync(string id, string passwd, string operation, string reference, string parameterxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartfreight.com/online/SFOv1/Enquiry", ReplyAction="http://www.smartfreight.com/online/SFOv1/EnquiryResponse")]
        System.Threading.Tasks.Task<string> EnquiryAsync(string id, string passwd, string conid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartfreight.com/online/SFOv1/FindCon", ReplyAction="http://www.smartfreight.com/online/SFOv1/FindConResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> FindConAsync(string id, string passwd, string xmlfield, string fieldvalue, string searchrepository);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartfreight.com/online/SFOv1/UpdateCon", ReplyAction="http://www.smartfreight.com/online/SFOv1/UpdateConResponse")]
        System.Threading.Tasks.Task<string> UpdateConAsync(string id, string passwd, string conid, string consignmentxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartfreight.com/online/SFOv1/DeleteCon", ReplyAction="http://www.smartfreight.com/online/SFOv1/DeleteConResponse")]
        System.Threading.Tasks.Task<string> DeleteConAsync(string id, string passwd, string conid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartfreight.com/online/SFOv1/TrackingEvents", ReplyAction="http://www.smartfreight.com/online/SFOv1/TrackingEventsResponse")]
        System.Threading.Tasks.Task<string> TrackingEventsAsync(string id, string passwd, string conid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    internal interface SFOv1Channel : DentalDrill.SmartFreight.Client.SFOv1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    internal partial class SFOv1Client : System.ServiceModel.ClientBase<DentalDrill.SmartFreight.Client.SFOv1>, DentalDrill.SmartFreight.Client.SFOv1
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SFOv1Client() : 
                base(SFOv1Client.GetDefaultBinding(), SFOv1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_SFOv1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SFOv1Client(EndpointConfiguration endpointConfiguration) : 
                base(SFOv1Client.GetBindingForEndpoint(endpointConfiguration), SFOv1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SFOv1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SFOv1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SFOv1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SFOv1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SFOv1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> ImportAsync(string id, string passwd, string reference, string consignmentxml)
        {
            return base.Channel.ImportAsync(id, passwd, reference, consignmentxml);
        }
        
        public System.Threading.Tasks.Task<string> CostComparisonAsync(string id, string passwd, string reference, string consignmentxml)
        {
            return base.Channel.CostComparisonAsync(id, passwd, reference, consignmentxml);
        }
        
        public System.Threading.Tasks.Task<string> CalculateRateAsync(string id, string passwd, string reference, string consignmentxml)
        {
            return base.Channel.CalculateRateAsync(id, passwd, reference, consignmentxml);
        }
        
        public System.Threading.Tasks.Task<string> SOAPRequestAsync(string id, string passwd, string operation, string reference, string parameterxml)
        {
            return base.Channel.SOAPRequestAsync(id, passwd, operation, reference, parameterxml);
        }
        
        public System.Threading.Tasks.Task<string> EnquiryAsync(string id, string passwd, string conid)
        {
            return base.Channel.EnquiryAsync(id, passwd, conid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> FindConAsync(string id, string passwd, string xmlfield, string fieldvalue, string searchrepository)
        {
            return base.Channel.FindConAsync(id, passwd, xmlfield, fieldvalue, searchrepository);
        }
        
        public System.Threading.Tasks.Task<string> UpdateConAsync(string id, string passwd, string conid, string consignmentxml)
        {
            return base.Channel.UpdateConAsync(id, passwd, conid, consignmentxml);
        }
        
        public System.Threading.Tasks.Task<string> DeleteConAsync(string id, string passwd, string conid)
        {
            return base.Channel.DeleteConAsync(id, passwd, conid);
        }
        
        public System.Threading.Tasks.Task<string> TrackingEventsAsync(string id, string passwd, string conid)
        {
            return base.Channel.TrackingEventsAsync(id, passwd, conid);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_SFOv1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_SFOv1))
            {
                return new System.ServiceModel.EndpointAddress("https://api-r1.smartfreight.com/api/soap/classic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SFOv1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_SFOv1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SFOv1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_SFOv1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_SFOv1,
        }
    }
}
